### ISSUE TITLE
How to construct a VertexBuffer when i already have a large vertex array?

### ISSUE THREAD

**Issue by linuxaged** [tomaka/glium#1036]
After deserializing from file I got a large vertex array which contains thousands vertices.

The common way to construct VertexBuffer becomes unacceptable in this situation:

    #[derive(Copy, Clone)]
    struct Vertex {
        position: [f64; 3],
    }

    implement_vertex!(Vertex, position);

    let vertex1 = Vertex { position: [-0.5, -0.5] };
    let vertex2 = Vertex { position: [ 0.0,  0.5] };
    let vertex3 = Vertex { position: [ 0.5, -0.25] };
    ...
    thousands
    ...
    let shape = vec![vertex1, vertex2, vertex3, ...];

How to do it effectively?

**Comment by tomaka** [comment]
The easiest and fastest way is to create an empty buffer and then map it:

```rust
let vb = glium::VertexBuffer::empty(&display, number_of_elements);
let mut mapping = vb.map();
mapping[0].position = ...;
mapping[1].position = ...;
...
```

And you deserialize your vertices directly into the mapped buffer.
