### ISSUE TITLE
Can't pass a per-instance matrix to a shader

### ISSUE THREAD

**Issue by camjackson** [tomaka/glium#1046]
I'm not sure whether this is a bug in Glium, or just me getting something wrong - probably the latter.

I want my shader to take a view matrix (and eventually a projection matrix) as a uniform, and a model matrix that's constant per instance. At the moment I can get it to work if I specify the model translation and scaling as separate `vec3`s, and construct the model transform matrix in GLSL, but I can't seem to get it to work when I construct the model transform matrix in Rust and pass it in as a single `mat4`.

My shader right now:

```glsl
#version 140

uniform mat4 view_transform; //works

in vec3 vertex_position; //works

in vec3 model_position; //works
in vec3 model_scale; //works
in mat4 model_transform; //does not work :(

in vec3 vertex_color;
out vec3 vColor;

void main() {
    //building the model transform from its 2 parts - this works
    mat4 m_t = mat4(
            vec4(model_scale.x, 0.0, 0.0, 0.0),
            vec4(0.0, model_scale.y, 0.0, 0.0),
            vec4(0.0, 0.0, model_scale.z, 0.0),
            vec4(model_position, 1.0)
    );
    gl_Position = view_transform * m_t * vec4(vertex_position, 1.0); //this renders correctly

    //If I comment out the line above and use this one, it renders nothing at all
    //gl_Position = view_transform * model_transform * vec4(vertex_position, 1.0);

    vColor = vertex_color;
}
```
The code that's generating the instances looks like this:

```rust
fn instances(&self, transforms: &Vec<Transform>) -> VertexBufferAny {
    #[derive(Copy, Clone)]
    struct ModelTransform {
        model_transform: [[f32; 4]; 4], //Is this the right type for a mat4? That's what the uniforms use
        model_position: [f32; 3],
        model_scale: [f32; 3],
    }

    implement_vertex!(ModelTransform, model_transform, model_position, model_scale);

    let mut data = Vec::new();
    for t in transforms.iter() {
        if t.visible {
            data.push(ModelTransform {
                model_transform: [     //I want to construct the matrix here, not in GLSL, but it doesn't work
                    [t.scale_x, 0., 0., 0.],
                    [0., t.scale_y, 0., 0.],
                    [0., 0., t.scale_z, 0.],
                    [t.x, t.y, t.z, 1.],
                ],
                //I want to delete the next 2 lines, but at the moment I need them
                model_position: [t.x, t.y, t.z],
                model_scale: [t.scale_x, t.scale_y, t.scale_z],
            })
        }
    }
    VertexBuffer::new(&self.display, data).into_vertex_buffer_any()
}
```

The draw call is something like:

```rust
frame.draw((&vertices, instances.per_instance_if_supported().unwrap()),
    &indices, &program, &uniforms, &std::default::Default::default()
).unwrap();
```

I searched through all the Glium examples, and it turns out there's no example of a non-uniform matrix being passed to a shader. I wouldn't have thought that passing a matrix would be different depending on whether it's a uniform or not, but I can't figure out what I'm doing wrong?

**Comment by tomaka** [comment]
This is a bug in glium, the implementation isn't complete :-/

**Comment by camjackson** [comment]
Oh I see! Is there more info somewhere on what exactly is incomplete? Can I help?

**Comment by tomaka** [comment]
The code here should be reworked: https://github.com/tomaka/glium/blob/master/src/vertex_array_object.rs#L462-L483

When you declare `attribute mat4 matrix;` in your shader code, in reality it creates four different bindings points as if you had four `vec4` attributes.

So to pass a matrix, you must call `glVertexAttribIPointer` four times, with `attribute.location`, `attribute.location + 1`, `attribute.location + 2` and `attribute.location + 3` (and ajust the offset of the data as well)

**Comment by camjackson** [comment]
Doesn't look too tricky, I'll have a go at it.

**Comment by camjackson** [comment]
Hmm, is there a reason none of the `FLOAT` types are matched against? Just hasn't been done yet, or are they meant to fall through to the `_` case?

**Comment by camjackson** [comment]
Also, the types like `gl::DOUBLE_VEC2` are never returned from `vertex_binding_type_to_gl`, it returns `(gl::DOUBLE, 3)` instead. Is intended, or just incomplete?

**Comment by tomaka** [comment]
`glVertexAttribPointer` is for single-precision floating points, `glVertexAttribIPointer` for integers, and `glVertexAttribLPointer` for double-precision floats.

These functions should only take basic types, like `FLOAT` or `INT` (and not `FLOAT_VEC2` for example). `vertex_binding_types_to_gl` sometimes returns `FLOAT_MAT4` for example, this is forbidden as well.

This function has a lot of problems :-/

**Comment by camjackson** [comment]
Ah, I see. So, you said earlier that a matrix needs to be done as 4 vecs... Are vecs just done in the same way as floats? Or floats/vecs/mats all different?

I'm pretty new to OpenGL, but I might have another go at this tomorrow if I can.

**Comment by tomaka** [comment]
If you have a single float, you pass `FLOAT` and `1` to the function. If you have a `vec4` you pass `FLOAT` and `4`. And for a matrix it's the same as multiple vecs.

**Comment by tomaka** [comment]
Also note that the function should take the format of the data in the vertex buffer.
For example if the shader expects an `int` you can pass a `FLOAT` instead, in which case OpenGL will perform the conversion.
