### ISSUE TITLE
Add support for U64 attributes

### ISSUE THREAD

**Issue by tomaka** [tomaka/glium#1056]

**Comment by camjackson** [comment]
How about I64?

**Comment by tomaka** [comment]
Sure, I64 as well.

The problem with U64/I64 is that they are supported only by modern cards. For the moment we don't check whether the backend supports vertex attributes. This hasn't been a problem so far, but it will become one if we add U64/I64.

**Comment by tomaka** [comment]
Closing in favor of #1077
