### ISSUE TITLE
Consider adding a lifetime to Facade and Context

### ISSUE THREAD

**Issue by nukep** [tomaka/glium#1111]
I'm working on improving the soundness of the `rust-sdl2` API. Some new changes include giving `sdl2::video::Window` a lifetime so that it doesn't outlive the "video subsystem", i.e. `Window<'a>`. The OpenGL context created by SDL2 might also require a lifetime if it's destroyed by `SDL_Quit()`, but I'm [unsure](https://github.com/AngryLawyer/rust-sdl2/issues/437) if this is the case right now.

While updating `glium_sdl2`, I noticed that there's no way to restrict the lifetime of the `Context`. This currently makes it infeasible to store an SDL window in the backend.

Here's what I'm aiming to do in `glium_sdl2`, generally:

```rust
#[derive(Clone)]
pub struct SDL2Facade<'a> {
    // contains everything related to the current context and its state
    context: Rc<Context<'a>>,

    backend: Rc<SDL2WindowBackend<'a>>,
}

impl<'a> Facade<'a> for SDL2Facade<'a> {
    fn get_context(&self) -> &Rc<Context<'a>> { &self.context }
}

pub struct SDL2WindowBackend<'a> {
    window: UnsafeCell<sdl2::video::Window<'a>>,
    context: sdl2::video::GLContext   // may require <'a>?
}
```

```rust
let backend = Rc::new(try!(SDL2WindowBackend::new(self)));
// The line below is a compilation error in glium 0.7
let context = try!(unsafe { Context::new(backend.clone(), true) });
        
let display = SDL2Facade {
    context: context,
    backend: backend
};

Ok(display)
```
Any thoughts on this?

**Comment by tomaka** [comment]
All glium objects (buffers, programs, textures, etc.)  hold a `Rc<Context>`.
Adding a lifetime parameter to `Context` would require adding a lifetime parameter to all these objects and to the user's code.

**Comment by nukep** [comment]
Right. I agree that adding lifetime parameters to everything could be unwieldy, and doing so would be horrible for users.

Maybe there's a way to defer the lifetime check to run-time instead. If the Window/SDL_GLContext is destroyed, then the `Context` stops working. Is there a "kill switch" available for `Context`?

**Comment by tomaka** [comment]
You could treat this as a lost context.
When the window is destroyed, `is_current` returns false and `make_current` returns an error.

**Comment by nukep** [comment]
This can be closed. SDL's `Window` doesn't require a lifetime, and it now contains an `Rc` that quits SDL2 and the video subsystem.
