### ISSUE TITLE
UniformsStorage::values can get excessively large

### ISSUE THREAD

**Issue by PeterReid** [tomaka/glium#1144]
UniformStorage::values seems to expect uniform locations to be pretty small, but my OpenGL implementation gave back something over 21 million as the first uniform location. This made the triangle example immediately allocate about 1.5 GB and take a few seconds to start up as it extended `values` to include that index.

Replacing the SmallVec with a HashMap fixed this, but I imagine that will hurt performance a bit for people who get more reasonable locations. Something that switches between SmallVec and HashMap depending on slots filled vs slots allocated might work out better... I do not know enough about the context here to know what a typical workload on this might be.

If you have a preferred solution, I'm happy to implement it and do a pull request.

**Comment by tomaka** [comment]
There's also another possibility: if the value is too large, just ignore the caching and call `glUniform` anyway.

Is your implementation something special, or is it just a regular driver?
If it is common for implementations to return large numbers, a `HashMap` would be better.

**Comment by PeterReid** [comment]
My OpenGL implementation is nothing special -- I have a Geforce card and Nvidia driver on Windows, which I assume is doing this.

**Comment by tomaka** [comment]
Ok, so a hashmap is probably preferred.
