### ISSUE TITLE
Problem enable sRGB

### ISSUE THREAD

**Issue by Yamakaky** [tomaka/glium#1185]
```rust
// building the display, ie. the main object
let display = glutin::WindowBuilder::new()
        .with_title(format!("Snake 3D effect"))
        .with_srgb(Some(true))
        .build_glium();
assert_eq(display, Err(BackendCreationError(NoAvailablePixelFormat)));
```
I have en intel HD3000. Any idea ?

**Comment by tomaka** [comment]
This is a glutin issue and not a glium issue, since it is about context creation.

It's also a known problem on Linux (are you on Linux?). For some reason the GLX & EGL APIs always report sRGB as false, even when the formats actually have sRGB enabled.
