### ISSUE TITLE
Cannot get example to run on linux due to cyclic package dependency (winapi v0.2.2)

### ISSUE THREAD

**Issue by whackashoe** [tomaka/glium#1189]
Hi!

I have copied the basic steps from the first part of the tutorial. On running `cargo build` it errors with this output:

        Updating registry `https://github.com/rust-lang/crates.io-index`
    cyclic package dependency: package `winapi v0.2.2` depends on itself

My Cargo.toml looks like this:

    [package]
    
    name = "dronesim_rs"
    version = "0.0.1"
    authors = ["Jett <whackashoe@gmail.com>"]
    
    [dependencies]
    glium = "*"

This is on Ubuntu 14.04 64 bit.

**Comment by tomaka** [comment]
cc @retep998
An idea?

**Comment by retep998** [comment]
What. How does this even.
What is your cargo version?

**Comment by whackashoe** [comment]
Clearly out of date, I just did rustup.sh and looks like this error is resolved, seems something was too old to work properly. Apologies, in haste I didn't check my version prior! Quite strange error to arise from old cargo though, eh?
