### ISSUE TITLE
Handle interface block layout

### ISSUE THREAD

**Issue by msiglreith** [tomaka/glium#1203]
Offset and alignment of blocks should be handled correctly. The current implementation seems to ignore the memory layout. The following code snippet fails as `pos` is aligned to the base alignment of `vec4`
```GLSL
// GLSL code
uniform layout(std140);
uniform Light {
    vec3 pos;
    vec3 color;
};
```
```Rust
// host code
#[derive(Copy, Clone)]
struct LightData {
    pos: [f32; 3],
    color: [f32; 3],
}

implement_uniform_block!(LightData, pos, color);
```

**Comment by tomaka** [comment]
The offset/alignment is supposed to be checked when you draw. That's what `DrawError::UniformBlockLayoutMismatch` and `LayoutMismatchError` are for.

Could you give more information about what fails? A panic? No error and the shader not working?

Note that it is well-known that some drivers sometimes don't respect the standard when it comes to alignment of `vec3`s. However glium queries the data from the implementation, so it shouldn't trigger bugs.

**Comment by msiglreith** [comment]
Here is the output from the console:
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: UniformBlockLayoutMismatch { name: "Light", err: MemberMismatch { member: "color", err: OffsetMismatch { expected: 16, obtained: 12 } } }', ../src/libcore\result.rs:734
```
The error occurs on submitting a draw call with the fragment shader. `target.draw(&vertex_buffer, &index_buffer, &program, &uniforms, &Default::default()).unwrap();`

**Comment by tomaka** [comment]
Well, that's the expected behavior.
Glium can't align data for you. You have to use something like this: https://github.com/tomaka/glium/blob/master/examples/gpgpu.rs#L33

**Comment by msiglreith** [comment]
Ok, thanks (:
Closing this.
