### ISSUE TITLE
Include an example, like with glutin

### ISSUE THREAD

**Issue by bmcorser** [tomaka/glium#1204]
I really like how I can just `cargo run --example window` to get some working code to poke around with in glutin.

Could something similar be provided for glium?

**Comment by tomaka** [comment]
Everything in [the "examples" directory](https://github.com/tomaka/glium/tree/master/examples) can be run with `cargo run --example foo`.

**Comment by bmcorser** [comment]
Ah, that's a cargo trope I missed then.

I get a boat load (26) of compiler errors when I try to run the examples, but that might another issue.

Closing this :+1:
