### ISSUE TITLE
examples/tutorial-03b compiles but panics with UniformTypeMismatch error

### ISSUE THREAD

**Issue by caldwell** [tomaka/glium#1221]
I did a clone of the repo and tried to build the `tutorial-03b` example like this:

    $ cargo build --example tutorial-03b
    [lots of output]
    $ ./target/debug/examples/tutorial-03b
    thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: UniformTypeMismatch { name: "matrix", expected: FloatMat4 }', ../src/libcore/result.rs:734

**Comment by stubiklaus** [comment]
I get this Kind of Error for the float
```
target.draw(&vertex_buffer, &indices, &program, &uniform! { t: t },
            &Default::default()).unwrap();
```

Message is
```
UniformTypeMismatch { name: "t", expected: Float }
```

**Comment by tomaka** [comment]
@stubiklaus You need to make sure that `t` (the Rust variable) is an `f32` and not an `f64`.
By default if you write `let t = 0.0;`, `t` is an `f64`.

Reopening this issue to mention this in the tutorial.

**Comment by tomaka** [comment]
For the record, this wasn't a problem in the past because `f64` uniforms weren't implemented and Rust automatically inferred the types as `f32`.

However there's no clean solution to this solution except fix existing code to make sure that all the values are f32s :-/

**Comment by stubiklaus** [comment]
Hi thanks for your answer.
I found another solution .
My solution was to anotate the type at declaration 
```
let mut t : f32 = -0.5;
```
