### ISSUE TITLE
Initialization error on Intel HD 2000

### ISSUE THREAD

**Issue by trgk** [tomaka/glium#1236]
Running even the first tutorial code results in OpenGL initialization error, despite that, the program doesn't panic and basic things work. Trying to use uniforms just hangs the system.

Building a pure glutin window doesn't trigger the error.

GL Intercept logs show the following:
>GL ERROR - Function glGetFramebufferAttachmentParameteriv(GL_FRAMEBUFFER,GL_BACK_LEFT,GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING,0000000000220DD0) generated error GL_INVALID_OPERATION
GLDriver::DeleteOpenGLContext - Deleting current context 0000000000020000?

Full logs: http://pastebin.com/R3TWFKeS

Win 7 x64, integrated Intel HD 2000, driver version 15.28.24.64.4229

**Comment by tomaka** [comment]
Thanks for the report.

In theory that means that you don't have a back left buffer, which is weird.

> Trying to use uniforms just hangs the system.

That's a entire different problem :-/

The buggy initialization code only determines whether the framebuffer is in RGB or sRGB. This information isn't used at all in glium and is only here so that the user can query it.

**Comment by trgk** [comment]
Hm, that's strange.
I tried running the uniform example a couple more times. 
It opens a window, though doesn't render anything in it, then, in a couple of seconds, the system hangs. Closing window doesn't kill the process and the system still hangs.

After reading the logs it looks like the program fails to get context and then everything fails(though I might be wrong, still dabbling in both OpenGL and Rust).

Logs: http://pastebin.com/PjZU5yGk
Something wrong with my GPU probably?

**Comment by tomaka** [comment]
Ah, I think I know where it comes from!

> glGetUniformLocation(3,"t")=23724032

This causes glium to allocate an array of `23724033` elements.

This is issue #1144 that was fixed by #1209. However the change isn't published on crates.io yet.

If you have some time, could you please try if the github version of glium works?

**Comment by trgk** [comment]
Yes, tried that and it works. Thanks a lot for your help.
Anything I shall do with that buffer error?

**Comment by tomaka** [comment]
There were already a lot of problems with the other calls to `glGetFramebufferAttachmentParameteriv`.

Calling this function should be avoided if possible. And if it's not possible, glium should check whether the attachment exist before querying the parameter of the attachment.

I'm going to attempt a fix in the next few days.

**Comment by tomaka** [comment]
My hypothesis is that the pixel format selected by glutin doesn't have double buffering.

I opened #1237 but I'm not sure this is the right fix.
