### ISSUE TITLE
Cannot use nalgebra::Mat4 in uniforms

### ISSUE THREAD

**Issue by matklad** [tomaka/glium#1253]
May be I am doing something completely wrong, but I can't use na::Mat4 as a uniform. I guess it should be possible, because there is an impl of AsUniformValue for Mat4: https://github.com/tomaka/glium/blob/master/src/uniforms/value.rs#L709

The error I get is 
```
the trait `glium::uniforms::AsUniformValue` is not implemented for the type `nalgebra::structs::mat::Mat4<f32>`
```

I have enable nalgebra feature in toml file: 

```
[dependencies.glium]
version = "*"
features = ["nalgebra", "cgmath", "glutin"]
default-features = false
```

and I do import the trait: `use glium::uniforms::*;`

**Comment by tomaka** [comment]
Maybe you're using nalgebra 0.3? Glium depends on version 0.2.

**Comment by matklad** [comment]
Yes, you are right, thanks!
