### ISSUE TITLE
Panic XNotSupported running on Raspbian (Raspberry Pi)

### ISSUE THREAD

**Issue by pentagolo** [tomaka/glium#1255]
I cross-compiled the application
```rust
#[macro_use]
extern crate glium;
fn main() {
	let display = glium::glutin::WindowBuilder::new().build_glium();
}
```
with the Cargo.toml
```
[dependencies]
glium = "*"
```
using a cross-compiler as explained at https://github.com/Ogeon/rust-on-raspberry-pi.
Notice that i do not call unwrap on the result, so the variable display is of type ```std::result::Result<_, _>```.

On raspbian i started X, opened a terminal and started the application. The error
```
thread '<main>' panicked at 'callled `Result::unwrap()` on an `Err` value: XNotSupported', src/libcore/result.rs:731
```
was reported.

There is a function calling unwrap inside the glium::glutin lib thats causing the panic. I think this should be reported as an error-result instead.

But what can i do to make it run on the Raspberry Pi?

**Comment by tomaka** [comment]
Could you open an issue in glutin instead?

The exact problem is that one of the libraries of raspbian is missing symbols for an unknown reason.
