### ISSUE TITLE
running through the tutorials fails

### ISSUE THREAD

**Issue by krux02** [tomaka/glium#1265]
Hi, Im new to rust, and just started with a [tutorial](http://tomaka.github.io/glium/book/tuto-01-getting-started.html), but I get an error when it is compiling it's dependencies. This is what I get:

[cargo build error](http://pastebin.com/QYB4TaYR)

some versions:

    cargo 0.5.0-nightly (1c27185 2015-08-28)
    rustc 1.3.0

**Comment by tomaka** [comment]
This is due to a stupid mistake in gl-rs :-/

Should be fixed in around half an hour. Sorry for this.
