### ISSUE TITLE
GSGL 'inverse' undeclared in tutorial

### ISSUE THREAD

**Issue by palango** [tomaka/glium#1272]
I followed the tutorial/book. In the chapter about Gouraud shading I always get an error about the GSGL `inverse` function.

```
     Running `target/debug/gltest`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("ERROR: 0:8: Invalid call of undeclared identifier \'inverse\'\n")', ../src/libcore/result.rs:732
```

I'm on a mid-2013 MacBook Air with OS X 10.11 with Rust 1.3 stable.

**Comment by tomaka** [comment]
The function is likely not implemented :-/

**Comment by RGafiyatullin** [comment]
1) The function is available for OSX if GLSL version "400" is specified.

2) @tomaka, the matrix seems to be the same for each vertex -- isn't it better to invert it once in the CPU and then put inverted into the uniform?

**Comment by tomaka** [comment]
> isn't it better to invert it once in the CPU and then put inverted into the uniform?

Yeah that's what you usually do in a real game or engine. But it's a bit tedious to write an `invert` function in Rust, and out of scope of the tutorial.

**Comment by RGafiyatullin** [comment]
@tomaka, sorry for slightly diverging from the original topic. And probably the question is silly.
Nevertheless, what would you recommend to use to do Matrix/Vector arithmetics when needed in an application using Glium?
Implementing by myself 'invert' or 'multiply' (just to name a few) seems to be a bit wrong.

**Comment by tomaka** [comment]
There's nalgebra and cgmath. Cgmath is more oriented towards gamedev.

**Comment by tomaka** [comment]
Closing in favor of #1311
