### ISSUE TITLE
Test array_layout_offsets fails

### ISSUE THREAD

**Issue by nicokoch** [tomaka/glium#1291]
System is the same as described in #1290 
```
failures:

---- array_layout_offsets stdout ----
        thread 'array_layout_offsets' panicked at 'assertion failed: `(left == right)` (left: `Struct { members: [("data", Array { content: Struct { members: [("pos", BasicType { ty: FloatVec2, offset_in_buffer: 224 }), ("dir", BasicType { ty: FloatVec2, offset_in_buffer: 8 }), ("speed", BasicType { ty: Float, offset_in_buffer: 2832 })] }, length: 256 })] }`, right: `Struct { members: [("data", Array { content: Struct { members: [("pos", BasicType { ty: FloatVec2, offset_in_buffer: 0 }), ("dir", BasicType { ty: FloatVec2, offset_in_buffer: 8 }), ("speed", BasicType { ty: Float, offset_in_buffer: 16 })] }, length: 256 })] }`)', tests\shaders.rs:834


failures:
    array_layout_offsets
```

**Comment by adamcavendish** [comment]
(HARDWARE INFO: Nvidia GT560M)

Also failed at `array_layout_offsets`:

---- array_layout_offsets stdout ----
	thread 'array_layout_offsets' panicked at 'assertion failed: `(left == right)` (left: `Struct { members: [("data", Array { content: Struct { members: [("dir", BasicType { ty: FloatVec2, offset_in_buffer: 8 }), ("pos", BasicType { ty: FloatVec2, offset_in_buffer: 0 }), ("speed", BasicType { ty: Float, offset_in_buffer: 16 })] }, length: 256 })] }`, right: `Struct { members: [("data", Array { content: Struct { members: [("pos", BasicType { ty: FloatVec2, offset_in_buffer: 0 }), ("dir", BasicType { ty: FloatVec2, offset_in_buffer: 8 }), ("speed", BasicType { ty: Float, offset_in_buffer: 16 })] }, length: 256 })] }`)', tests/shaders.rs:834

**Comment by nicokoch** [comment]
The test does no longer fail on my system, so maybe this issue can be closed?
