### ISSUE TITLE
Tutorial 08 doesn't run

### ISSUE THREAD

**Issue by am0d** [tomaka/glium#1311]
While running step 8 of the tutorial, I ran into the following error:

    thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("0(12) : error C7532: global function inverse requires \"#version 150\" or later\n0(12) : error C0000: ... or #extension GL_ARB_gpu_shader5 : enable\n")', ../src/libcore\result.rs:731
    An unknown error occurred

**Comment by tomaka** [comment]
Ah, that's a useful message!

See also #1272

**Comment by am0d** [comment]
I changed the version to 150, and it did run fine.
