### ISSUE TITLE
Implementation of AsUniformValue for [i16; 2]

### ISSUE THREAD

**Issue by Yamakaky** [tomaka/glium#1315]
It's only implemented for [ui]32 and [ui]64. It could also be implemented for u8.

**Comment by tomaka** [comment]
The type on which the trait is implement map to what OpenGL accepts. OpenGL doesn't accept i8/u8/i16/u16.

**Comment by Yamakaky** [comment]
Looks like glsl only support 32 and 64 bits variables. Should we implement AsUniformValue with a convertion to u32/i32 ?
