### ISSUE TITLE
Warning on binding an unknown uniform

### ISSUE THREAD

**Issue by msiglreith** [tomaka/glium#1332]
Glium should probably output a warning if you tried to bind a uniform, which isn't in the actual shader code. (Not an error as it could be optimized out by the shader compiler?)

Example: shader buffer: `InputFFT` and in uniforms: `inputFFT`
```Rust
let fft_compute_src = r#"
       #version 430
		layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
		layout(std430) buffer InputFFT {
			vec2 fft_input[];
		};
		
		layout(std430) buffer OutputFFT {
			vec2 fft_output[];
		};
		
		uniform uint block_size;
		uniform uint num_threads;

		void main() {
           [..]
		}
    "#;
fft_compute.execute(uniform!{inputFFT: fft_input,
						outputFFT: fft_output,
						num_threads: num_threads,
						block_size: block_size
					},
					1, 1, 1);
```

**Comment by tomaka** [comment]
How would you output a warning? With println?
There's no good way to report this.

**Comment by nicokoch** [comment]
> How would you output a warning? With println?
> As far as I know there's no good way to report this.

You could use the log crate, which is only a logging interface.
There would be no runtime overhead if no actual logging implementation is used in a crate that uses glium, but they would get the warning if they use a logging implementation.

**Comment by msiglreith** [comment]
>How would you output a warning? With println?
>As far as I know there's no good way to report this.

Using `println` was my first idea until I noticed that it is used only at one place. Looks like there is indeed no really good way besides console output, which I actually dislike as we there is no way to say if the uniform is just inactive due to the compiler, resulting in unnecessary output.

Maybe simply mention it in the docs at some point and close this.

**Comment by msiglreith** [comment]
Closed in favor of https://github.com/tomaka/glium/issues/1388
(Better way of dealing with this)
