### ISSUE TITLE
Consider upgrading libc to 0.2

### ISSUE THREAD

**Issue by aloucks** [tomaka/glium#1333]
Issues with libc are cropping up when making custom backends. Specifically, GLFW has the libc dependency defined as `libc = "*"`. 
```
21:6 error: method `get_proc_address` has an incompatible type for trait:
 expected enum `libc::types::common::c95::c_void`,
    found enum `libc::c_void` [E0053]
src\glium_backend.rs:19     unsafe fn get_proc_address(&self, procname: &str) -> *const libc::c_void
```

**Comment by tomaka** [comment]
Switching to `libc 0.2` within glium itself requires gl_generator to update to libc 0.2

However there's a better change: modify the `Backend` trait to replace `libc::c_void` with `()`, so that all errors go away.
