### ISSUE TITLE
tracking: backtrace crate update

### ISSUE THREAD

**Issue by luzvioleta** [tomaka/glium#1334]
I've recently cloned glium at my workplace to start diving into the code, and got breakage by one dependency pulling other version of `kernel32-sys` (and maybe libc? the published version on crates.io uses 0.1, but a git commit after that imports 0.2)

```
native library `kernel32` is being linked to by more than one package, and can only be linked to by one package

  kernel32-sys v0.1.4
  kernel32-sys v0.2.0
```
so I submitted a request for updated dependencies there and left this issue here for reference → alexcrichton/backtrace-rs#6

**Comment by bvssvni** [comment]
backtrace is now updated.

**Comment by lfairy** [comment]
Should this issue be closed?
