### ISSUE TITLE
Tutorial 06 does not compile

### ISSUE THREAD

**Issue by KalitaAlexey** [tomaka/glium#1345]
src/main.rs:18:19: 18:49 error: the trait `glium::texture::Texture2dDataSource<'_>` is not implemented for the type `image::dynimage::DynamicImage` [E0277]
src/main.rs:18     let texture = glium::texture::Texture2d::new(&display, image).unwrap();
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.rs:18:19: 18:49 help: run `rustc --explain E0277` to see a detailed explanation
src/main.rs:18:19: 18:49 note: required by `glium::texture::texture2d::Texture2d::new`
error: aborting due to previous error

**Comment by tomaka** [comment]
It's because of a version mismatch between the `image` library and the version of `image` used by glium.

This is going to be fixed by #1337 

For the moment you need to put `image = "0.4"` in your Cargo.toml.

**Comment by KalitaAlexey** [comment]
Thanks.
