### ISSUE TITLE
Force Touch causes weird behavior

### ISSUE THREAD

**Issue by cptroot** [tomaka/glium#1369]
Using the force touch behavior on my apple trackpad causes ups and downs to no longer be in sync.

**Comment by bjz** [comment]
Would be nice to have a look at the Cocoa API to see how you are meant to handle this.Unfortunately I doubt many people have force touch devices to test it on yet. :(

**Comment by tomaka** [comment]
Could you reopen this issue on glutin instead, and then close this one?

**Comment by cptroot** [comment]
Closed in favor of tomaka/glutin#672
