### ISSUE TITLE
view matrix of camera.rs in examples is flawed

### ISSUE THREAD

**Issue by Roxxik** [tomaka/glium#1381]
If you look almost straigt up or down with this camera setting you are getting a skewed image.

try it yourself by adding

    camera.set_direction((0.0,1.0,0.2));
    camera.set_position((0.0,1.0,0.5));
to the teapot.rs right after creating the camera
and you'll see a pretty slim teapot

I found a quick fix, but I'm not totally sure whether this is the correct thing to do:
replace (in the sense of search and replace) every s_norm by s in

    support::camera::CameraState::get_view

The same error is in the book in tutorial 12.

**Comment by tomaka** [comment]
Ah, nice find!

The real fix is in fact to replace `s` with `s_norm` when building the final matrix.
