### ISSUE TITLE
match patterns

### ISSUE THREAD

**Issue by Roxxik** [tomaka/glium#1386]
example enum:

    enum E {
        a,
        b { c: u32 },
    }

there is a lot of 

    match e {
        &e::a => ... ,
        &e::b { ref c } => ... ,
    }

that can be replaced by

    match *e {
        e::a => ... ,
        e::b { ref c } => ... ,
    }

where `e` is a reference to this enum

Note: this needs to be `ref c` because e is just borrowed.

and there are a lot of matches on enums:
    
    match e {
        e::a => ... ,
        e::b { .. } => ... ,
    }

that can be replaced easily by:

    use self::E::*;
    match e {
        a => ... ,
        b { .. } => ... ,
    }

where e is an value of this enum

NOTE: if you only use C-like enums, then the `use` line can be omitted.

If i have some spare time, there will be a PR for this in a few days.

**Comment by tomaka** [comment]
I don't really see the point in changing that :o

**Comment by Roxxik** [comment]
That's more about code readability, because there are some pathological cases.
i.e.:

    match event {
        &glutin::Event::KeyboardInput(glutin::ElementState::Pressed, _, Some(glutin::VirtualKeyCode::Space)) => {
            self.moving_up = true;
        },
        ...
    }

which could be:

    match *event {
        KeyboardInput(Pressed, _, Some(Space)) => {
            self.moving_up = true;
        },
        ...
    }


And I personally dislike repeating stuff, if it does not have a runtime or readability impact

**Comment by Roxxik** [comment]
match self {
        &UncompressedFloatFormat::U8 => {
            version >= &Version(Api::GlEs, 3, 0) || extensions.gl_arb_texture_rg
        },
        &UncompressedFloatFormat::U8U8 => {
            version >= &Version(Api::GlEs, 3, 0) || extensions.gl_arb_texture_rg
        },
        //&UncompressedFloatFormat::U5U6U5 => true,
        &UncompressedFloatFormat::U8U8U8 => {
            version >= &Version(Api::GlEs, 3, 0) || extensions.gl_oes_rgb8_rgba8
        },
        &UncompressedFloatFormat::U4U4U4U4 => true,
        &UncompressedFloatFormat::U5U5U5U1 => true,
        &UncompressedFloatFormat::U8U8U8U8 => {
            version >= &Version(Api::GlEs, 3, 0) || extensions.gl_arm_rgba8 ||
            extensions.gl_oes_rgb8_rgba8
        },
        &UncompressedFloatFormat::U10U10U10U2 => version >= &Version(Api::GlEs, 3, 0),
        &UncompressedFloatFormat::F16 => version >= &Version(Api::GlEs, 3, 2),
        &UncompressedFloatFormat::F16F16 => version >= &Version(Api::GlEs, 3, 2),
        &UncompressedFloatFormat::F16F16F16F16 => version >= &Version(Api::GlEs, 3, 2),
        &UncompressedFloatFormat::F32 => version >= &Version(Api::GlEs, 3, 2),
        &UncompressedFloatFormat::F32F32 => version >= &Version(Api::GlEs, 3, 2),
        &UncompressedFloatFormat::F32F32F32F32 => version >= &Version(Api::GlEs, 3, 2),
        &UncompressedFloatFormat::F11F11F10 => version >= &Version(Api::GlEs, 3, 2),
        _ => false
    }

versus:

    use self::UncompressedFloatFormat::*;
    use Api::GlEs;
    match *self {
        U8 | U8U8 => version >= &Version(GlEs, 3, 0) || extensions.gl_arb_texture_rg,
        //U5U6U5 => true,
        U8U8U8 => version >= &Version(GlEs, 3, 0) || extensions.gl_oes_rgb8_rgba8,
        U4U4U4U4 | U5U5U5U1 => true,
        U8U8U8U8 => version >= &Version(GlEs, 3, 0) || extensions.gl_arm_rgba8 ||
            extensions.gl_oes_rgb8_rgba8,
        U10U10U10U2 |
        F16 |
        F16F16 |
        F16F16F16F16 |
        F32 |
        F32F32 |
        F32F32F32F32 |
        F11F11F10 => version >= &Version(GlEs, 3, 2),
        _ => false
    }

Note the `use` should be scoped to the match block otherwise this would pollute the global namespace too much.

**Comment by Roxxik** [comment]
Closing, because this is not going to be fixed, might be minded for future code
