### ISSUE TITLE
Expose GL_RENDERER, GL_VENDOR etc.

### ISSUE THREAD

**Issue by bitshifter** [tomaka/glium#1394]
I'm interested in querying the GL renderer and vendor strings, and possibly other information like what profile is being used.

I was looking at adding these myself since in theory it's easy to query, but I'm not sure where it would be appropriate to do so. It seemed like the Capabilities struct might be a good place?

**Comment by tomaka** [comment]
Yes, you can load the values in `capabilities.rs`, and then add methods to the `Context` object.

**Comment by bitshifter** [comment]
Finished in PR https://github.com/tomaka/glium/pull/1399
