### ISSUE TITLE
Saving an Attachments along with a SimpleFrameBuffer

### ISSUE THREAD

**Issue by Roxxik** [tomaka/glium#1395]
This is more of a Rust issue.
I want to save a Texture, a DepthRenderBuffer and a SimpleFrameBuffer in a struct. Rust doesn't allow this because I'd have to keep the RenderBuffer(and Texture) and a reference to the same (indirect in the SimpleFrameBuffer)
I think that's to ensure that I don't destruct the object, while keeping the reference.

Now back to glium:
Is there a way in glium to access the attachments of the SimpleFrameBuffer?
This way I would not have to save the Texture and the DepthRenderBuffer explicitly, because I could access them from the SimpleFrameBuffer.

**Comment by tomaka** [comment]
The `SimpleFrameBuffer` object was designed to be recreated every time you need it. The internal OpenGL framebuffer is decoupled from the `SimpleFrameBuffer`.

This needs some additional optimizations though.

**Comment by Roxxik** [comment]
Ah ok, i just though that I could reuse the SimpleFrameBuffer, to safe me from validating the same attachments over and over again.

**Comment by tomaka** [comment]
> to save me from validating the same attachments over and over again.

That's what I was thinking about when I talked about optimizations.
If glium has already an OpenGL framebuffer in the past with the same attachments, it doesn't need to validate them again.
