### ISSUE TITLE
"GL context creation failed" when running within GLSL-Debugger

### ISSUE THREAD

**Issue by MasonAsh** [tomaka/glium#1413]
I'm trying to debug my program using GLSL-Debugger. The program starts and executes fine when launching normally, but within GLSL-Debugger I get the following output:

```
[glutin] x error code=8 major=154 minor=34: BadMatch (invalid parameter attributes)!
[glutin] x error code=8 major=154 minor=34: BadMatch (invalid parameter attributes)!
[glutin] x error code=2 major=154 minor=34: BadValue (integer parameter out of range for operation)!
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: BackendCreationError(OsError("GL context creation failed"))', ../src/libcore/result.rs:738
```

The GL Trace window shows the last OpenGL related function executed before crashing is ```glXGetVisualFromFBConfig```.

Sometimes, but not consistently, I get the same problem when debugging with eclipse and rustdt.

I am running Ubuntu 14.04 with a GTX 770 and nvidia-352 driver.

**Comment by MasonAsh** [comment]
Turns out I get the same problem when using GLSL-Debugger with glxgears and glmark2 so it's probably a problem on my end.

**Comment by tomaka** [comment]
Note that the most recent version of glutin has some better error reporting.
If you want more infos about your errors, you should try it.
