### ISSUE TITLE
Mention column major ordering in Glium book

### ISSUE THREAD

**Issue by Charlesetc** [tomaka/glium#1418]
Hi

I was just reading the glium book -- it's extremely interesting and helpful. Thank you!

It took me a while, though, to realize that matrices in openGL follow a column major ordering. (This is my first look at openGL.) I could be wrong, but I don't think this is mentioned in the book and it's certainly an important piece of information for anyone new to openGL. So that's all, you might want to consider adding this to the book.

**Comment by kyrylo** [comment]
It's mentioned here: http://tomaka.github.io/glium/book/tuto-10-perspective.html

**Comment by Charlesetc** [comment]
Nice!
