### ISSUE TITLE
Segfault when running tutorial example with Nouveau driver (but not with Nvidia driver)

### ISSUE THREAD

**Issue by merehap** [tomaka/glium#1428]
While running the the tutorial code from section 1.2 ([here](https://github.com/tomaka/glium/blob/master/examples/tutorial-02.rs)), I encountered a segfault. With "cargo run --verbose", then output is the following:
   
```
Compiling gliumtutorial v0.1.0 (file:///home/sean/projects/gliumtutorial)
     Running `rustc src/main.rs --crate-name gliumtutorial --crate-type bin -g --out-dir /home/sean/projects/gliumtutorial/target/debug --emit=dep-info,link -L dependency=/home/sean/projects/gliumtutorial/target/debug -L dependency=/home/sean/projects/gliumtutorial/target/debug/deps --extern glium=/home/sean/projects/gliumtutorial/target/debug/deps/libglium-8713649d54a4f846.rlib`
     Running `target/debug/gliumtutorial`
Process didn't exit successfully: `target/debug/gliumtutorial` (signal: 11)
```

According to [this stackoverflow post](http://stackoverflow.com/questions/34058193/how-to-handle-an-unknown-error-occurred-when-running-a-rust-program), this indicates a segfault occurred.

This issue disappeared (the window rendered correctly and persisted) as soon as I switched to using the equivalent Nvidia driver for my system (please note that this is a different system than in #1427 ).

```
Processor: Intel® Core™ i5-3330 CPU @ 3.00GHz × 4
Graphics: GeForce GTX 660/PCIe/SSE2
OS: Ubuntu 15.10
OS Type: 64-bit

rust 0.7
glium v0.13.5
glutin v0.4.9

Nouveau driver glxinfo:
GLX version: 1.4
...
OpenGL vendor string: nouveau
OpenGL renderer string: Gallium 0.4 on NVE4
OpenGL core profile version string: 4.1 (Core Profile) Mesa 11.0.2
OpenGL core profile shading language version string: 4.10

```

Is there any other information that I can provide to help debug this?

**Comment by nicokoch** [comment]
This sounds very much like a segfault in mesa or nouveau. I've had this happen before with newer OpenGL features, even with the intel driver.

Can you post the relevant output of the `dmesg` command after the error occurs?

**Comment by merehap** [comment]
dmesg shows the following when the error occurs:

> [  194.483117] show_signal_msg: 39 callbacks suppressed
> [  194.483122] gliumtutorial[2070]: segfault at 8 ip 00007fc59187858c sp 00007ffd574cc410 error 4 in libdrm_nouveau.so.2.0.0[7fc591875000+6000]

Setting those environment variables results in a successful run of the program, with no errors on the console or in dmesg.

Does this indicate a bug in nouveau/mesa hardware rendering such that I should cut a ticket with them? Also, would it be possible to enhance error reporting in glium to spell out exactly what is happening in cases like this?

**Comment by tomaka** [comment]
> Also, would it be possible to enhance error reporting in glium to spell out exactly what is happening in cases like this?

At [this line](https://github.com/tomaka/glium/blob/81f0cb2ca69c65039353512ca3944c5880666d9d/build/main.rs#L147) you can replace `StructGenerator` with `DebugStructGenerator`.

Then you can run one of glium's examples with `cargo run --example teapot` and check the stdout to know which function exactly made the driver crash.

**Comment by merehap** [comment]
Cool. If I understand correctly "DrawArrays(4, 0, 3072)" is the failing OpenGL command:

```
sean@dmt:~/projects/glium$ cargo run --example teapot --verbose
...
[OpenGL] UniformMatrix4fv(1, 1, 0, 0x7ffcd1a8bbc0)
[OpenGL] UniformMatrix4fv(0, 1, 0, 0x7ffcd1a8ba70)
[OpenGL] Enable(2929)
[OpenGL] Enable(3024)
[OpenGL] Viewport(0, 0, 959, 744)
[OpenGL] DrawArrays(4, 0, 3072)
Process didn't exit successfully: `target/debug/examples/teapot` (signal: 11)

```
```
sean@dmt:~/projects/glium$ dmesg
...
[15766.305913] teapot[9067]: segfault at 8 ip 00007f5886e8058c sp 00007ffe216723b0 error 4 in libdrm_nouveau.so.2.0.0[7f5886e7d000+6000]
[15802.772473] teapot[9153]: segfault at 8 ip 00007f8847e8058c sp 00007ffcd1a8f760 error 4 in libdrm_nouveau.so.2.0.0[7f8847e7d000+6000]
```

Since DebugStructGenerator is clearly too verbose for normal use-cases, would it be possible to update origin/master with a custom StructGenerator (or equivalent) that, in the case of a segfault, outputs an error stating something like "The OpenGL graphics driver on this machine (nouveau 4.1/Mesa 11.0.2) segfaulted upon instruction 'DrawArrays(4, 0, 3072)'. Please file an issue against nouveau/Mesa at [website]." It seems that a message like this could save a lot of debug time for future glium clients.

Is there any other action that can be taken on this issue on the glium side (besides an error message), or has this investigation demonstrated this to be a non-issue in glium at this point?

**Comment by tomaka** [comment]
> Since DebugStructGenerator is clearly too verbose for normal use-cases, would it be possible to update origin/master with a custom StructGenerator (or equivalent) that, in the case of a segfault, outputs an error stating something like "The OpenGL graphics driver on this machine (nouveau 4.1/Mesa 11.0.2) segfaulted upon instruction 'DrawArrays(4, 0, 3072)'. Please file an issue against nouveau/Mesa at [website]." It seems that a message like this could save a lot of debug time for future glium clients.

That's not possible without adding a significant overhead to the library.

> Is there any other action that can be taken on this issue on the glium side (besides an error message), or has this investigation demonstrated this to be a non-issue in glium at this point?

I don't think there's anything more to do.
The teapot example doesn't use any of the advanced unsafe OpenGL feature, so a segfault technically can't be glium's fault.

**Comment by merehap** [comment]
OK, is it possible to catch an OpenGL segmentation fault and then print a custom error message? Or would this also impose too significant of overhead to glium?

**Comment by tomaka** [comment]
An OpenGL segfault is a regular segfault. Catching segfaults is a Rust issue and not a glium issue.
If you have debug symbols, a stack trace should show you which function was being executed.

**Comment by merehap** [comment]
Makes sense. Closing this now.

Thanks for you help, tomaka and nicokoch!
