### ISSUE TITLE
Why does creating a texture with data size mismatch panic?

### ISSUE THREAD

**Issue by birkenfeld** [tomaka/glium#1429]
The texture creation functions already return a `Result`, why is this case so special that it panics?

**Comment by tomaka** [comment]
Panicks are usually used when the problem is caused by a logic error in the user code, which is the case here.

**Comment by birkenfeld** [comment]
That is a valid design decision, and I guess the cases where the data and the dimensions come from different or dynamic sources are rare enough to warrant a check before creating the texture.
