### ISSUE TITLE
GLObject Trait on any Buffer Type ?

### ISSUE THREAD

**Issue by Kerosene2000** [tomaka/glium#1436]
Hello,

I am working on a program which need to `get_id()` of a `GLObject` from any `glium::buffer` type, it's needed by the [clCreateFromGLBuffer function](https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clCreateFromGLBuffer.html) and I saw that [glium::IndexBuffer](https://tomaka.github.io/glium/src/glium/index/buffer.rs.html#212) will loose the `GLObject Trait` implementation therefore it will not be possible to get the `GLObject id` ?

And why the `VertexBuffer` doesn't implement the `GLObject Trait` ?
Am I supposed to implement it myself ? (this is not a problem, this will not be difficult, this is just a question :smile: )

**Comment by tomaka** [comment]
I reworked buffers some time ago, and probably forgot to implement `GlObject` on this type. There is no fundamental reason why it is not implemented.

If you want to implement it yourself, I'd be happy to accept your PR!

**Comment by Kerosene2000** [comment]
I will work on this, but is it normal that `png 0.3.1` doesn't compile ?
```
$> rustc --version // stable rustc version
rustc 1.7.0 (a5d1e7a59 2016-02-29)
```

png multiple error messages like this: 
```
.../png-0.3.1/src/decoder/mod.rs:372:42: 372:60 error: unresolved name `TRANSFORM_EXPAND` [E0425]
.../png-0.3.1/src/decoder/mod.rs:372            GrayscaleAlpha if t.contains(::TRANSFORM_EXPAND) => 2 * 8,
```

**Comment by tomaka** [comment]
*grumble* The `image` library probably needs an update.

**Comment by Kerosene2000** [comment]
I change `image = "0.4.0"` to `image = "0.7.0"` and it seems to work !
