### ISSUE TITLE
GL_ARB_shader_subroutine extension not available pre-4.0 core for Nvidia

### ISSUE THREAD

**Issue by cybergeek94** [tomaka/glium#1439]
I am on Windows 10 64-bit running Nvidia 361.43 drivers on a GTX 980 Ti. When I try to run the `image_test` example for [`glium_graphics`](https://github.com/PistonDevelopers/glium_graphics), I get the following error (with `RUST_BACKTRACE=1`):

```
Running `target\debug\examples\image_test.exe`
thread '<main>' panicked at 'gl function was not loaded', C:\Users\cyber\Rust\glium_graphics\target\debug\build\glium-66cf141cfc3eb51d\out/gl_bindings.rs:7241
stack backtrace:
   0:     0x7ff6fae2007b - rt::lang_start::h62420155cfc3bacdoSz
   1:     0x7ff6fae1f48d - rt::lang_start::h62420155cfc3bacdoSz
   2:     0x7ff6fae1230f - sys_common::unwind::begin_unwind_inner::h39434662704a32f0oyt
   3:     0x7ff6facb6682 - begin_unwind<&str>
                        at C:\Users\cyber\Rust\src\libstd\sys\common\unwind\mod.rs:219
   4:     0x7ff6fad6d9cf - missing_fn_panic
                        at C:\Users\cyber\Rust\glium_graphics\<std macros>:3
   5:     0x7ff6fad0622f - GetProgramStageiv
                        at C:\Users\cyber\Rust\glium_graphics\target\debug\build\glium-66cf141cfc3eb51d\out\gl_bindings.rs:11492
   6:     0x7ff6fad04331 - reflect_subroutine_data
                        at C:\Users\cyber\AppData\Local\.multirust\cargo\registry\src\github.com-88ac128001ac3a9a\glium-0.13.5\src\program\reflection.rs:1139
   7:     0x7ff6fabf6b76 - from_shaders<glium_graphics::window::GliumWindow,&collections::vec::Vec<glium::program::shader::Shader>>
                        at C:\Users\cyber\AppData\Local\.multirust\cargo\registry\src\github.com-88ac128001ac3a9a\glium-0.13.5\src\program\raw.rs:170
   8:     0x7ff6fabf1224 - new<glium_graphics::window::GliumWindow,glium::program::ProgramCreationInput>
                        at C:\Users\cyber\AppData\Local\.multirust\cargo\registry\src\github.com-88ac128001ac3a9a\glium-0.13.5\src\program\program.rs:97
   9:     0x7ff6fabf0820 - from_source<glium_graphics::window::GliumWindow>
                        at C:\Users\cyber\AppData\Local\.multirust\cargo\registry\src\github.com-88ac128001ac3a9a\glium-0.13.5\src\program\program.rs:142
  10:     0x7ff6fabe43fe - new<glium_graphics::window::GliumWindow>
                        at C:\Users\cyber\Rust\glium_graphics\src\back_end.rs:49
  11:     0x7ff6fab21364 - main
                        at C:\Users\cyber\Rust\glium_graphics\examples\image_test.rs:30
  12:     0x7ff6fae1eea8 - rt::lang_start::h62420155cfc3bacdoSz
  13:     0x7ff6fae1a1e8 - sys_common::unwind::inner_try::hb0b28ccb354a3b71qvt
  14:     0x7ff6fae1ed2d - rt::lang_start::h62420155cfc3bacdoSz
  15:     0x7ff6fac42b99 - main
  16:     0x7ff6fae29df7 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264
  17:     0x7ff93f4e8101 - BaseThreadInitThunk
error: Process didn't exit successfully: `target\debug\examples\image_test.exe` (exit code: 101)
```

Which suggests that `GetProgramStageiv` did not load correctly. Switching the example to use an OpenGL 4.0 context or greater fixes this problem.

When using an OpenGL Extension Viewer, I see that the `GL_ARB_shader_subroutine` extension (which `GetProgramStageiv` is a part of) is not supported in the core profile until 4.0 for my Nvidia driver. However, this example runs fine on my Linux laptop, which is using Intel HD Graphics with an OpenGL 3.3 core profile. So I guess Nvidia dragged their feet when implementing this extension.

I'm not quite sure whose problem this actually is: this crate's, being the one that assumes that this function is loaded, or `glium_graphics`'. OpenGL 3.2 is a fine default otherwise; it's just that this extension doesn't load with a pre-4.0 core profile on Nvidia for some reason.

I do concede that my drivers are out-of-date; however, considering the problems people have been having with the latest ones, I'm somewhat hesitant to update. I don't think an update would address this problem anyways.

**Comment by cybergeek94** [comment]
Pinging @bvssvni as a major contributor to `glium_graphics` for input.

**Comment by tomaka** [comment]
It would be nice if you could add some `println`s here: https://github.com/tomaka/glium/blob/6aadf08fe39547ea99bac02c2943b2975498eb33/src/program/mod.rs#L46
...in order to know the values of `ctxt.get_version()` and `ctxt.get_extensions()`.

**Comment by cybergeek94** [comment]
https://gist.github.com/cybergeek94/9acccccdbab27b0b20e1

Of note:
```
Version(Gl, 3, 2)
ExtensionsList { .., gl_arb_shader_subroutine: true, .. }
```
Weird.

However, I also added the following tests after https://github.com/tomaka/glium/blob/6aadf08fe39547ea99bac02c2943b2975498eb33/src/context/mod.rs#L160:

```rust
let get_prog_stage_true = backend.get_proc_address("glGetProgramStageiv");
// There, I violated your privacy. Can I work for the NSA now?
let get_prog_stage: &(*const (), bool) = mem::transmute(&gl.GetProgramStageiv);
println!("{:?}, {:?}", get_prog_stage, get_prog_stage_true);
```

Which printed:
```
(0x7ff606747500, false), 0x0
```

So the backend is definitely returning a null pointer for `glGetProgramStageiv`. Should I transfer this issue to Glutin, then? (`glutin_window` is used for the examples)

**Comment by tomaka** [comment]
That's a bug in nVidia's drivers then.

Either your drivers are so out-of-date that they already fixed the bug, or we could add a little check in `is_subroutine_supported` to return false if the vendor is nVidia.

**Comment by cybergeek94** [comment]
But why is `ExtensionsList.gl_arb_shader_subroutine` being set to `true` if the function pointer fails to load?

**Comment by tomaka** [comment]
The list of extensions is provided by the driver and the function pointers are provided by the driver too.

The rules say that if you provide `GL_ARB_shader_subroutine` then you must provide `glGetProgramStageiv` as well. Your driver doesn't do that, hence the fact that it's a bug in it.

**Comment by nicokoch** [comment]
> Either your drivers are so out-of-date that they already fixed the bug, or we could add a little check in is_subroutine_supported to return false if the vendor is nVidia and the version inferior to 4.0.

But it's only broken on NVidia on windows. Nouveau works (and maybe Proprietary linux driver too, but didnt test).

**Comment by cybergeek94** [comment]
@nicokoch What is your driver version and release date?

**Comment by nicokoch** [comment]
I'm on mesa-git, checked out sometime around last week.

Note that what I tested has nothing to do with your windows driver. I was just pointing out that the fix proposed by tomaka wouldnt work. (Or does vendor not return nVidia for open source drivers?)

**Comment by Bobo1239** [comment]
The bug is still present in the latest Windows driver 364.72. No problems with the proprietary Linux driver (both stable (361.28) and beta (364.16)).

Nouveau return `nouveau` as vendor string.
