### ISSUE TITLE
Opening a Window on Windows with LTO panics

### ISSUE THREAD

**Issue by NeoLegends** [tomaka/glium#1446]
Trying to open a window like this:

```
let display = WindowBuilder::new()
    .with_dimensions(1280, 720)
    .with_title("Window Title")
    .with_visibility(true)
    .build_glium()
    .unwrap();
```

with LTO enabled panics like this:
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: BackendCreationError(OsError("CreateWindowEx function failed: Unzul\u{e4}ssiger Zugriff auf einen Speicherbereich. (os error 998)"))', ../src/libcore\result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
which roughly translates to `Invalid access to a memory region`.

Disabling LTO fixes the problem, but increases binary size.

**Comment by tomaka** [comment]
Could you try running one of glutin's examples to see if it works? It's probably a glutin issue and not glium issue.

**Comment by NeoLegends** [comment]
Yup, running the `window` example causes the same problem. This is indeed something with glutin. I will repost the issue there.
