### ISSUE TITLE
coveralls.io + github.com OAuth credentials need to be updated

### ISSUE THREAD

**Issue by bnewbold** [tomaka/glium#1456]
coveralls.io isn't showing actual source code diffs for coverage reports. The exact message is:

> SOURCE NOT AVAILABLE
> The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.

See, for example: https://coveralls.io/builds/5735092/source?filename=src%2Funiforms%2Fmod.rs

**Comment by tomaka** [comment]
Ugh.
I think it's ok now.

**Comment by bnewbold** [comment]
Unfortunately this still seems to be a problem as of a couple days ago:
https://coveralls.io/builds/6510103/source?filename=src%2Fsampler_object.rs
