### ISSUE TITLE
Vertex/Index Buffer with dynamic size?

### ISSUE THREAD

**Issue by WeAthFoLD** [tomaka/glium#1479]
I'm currently confused with how to transfer dynamic-sized data into a `VertexBuffer` object.

What I'm trying to do is rendering a Minecraft-y world base. The world is divided in lots of chunks. Each chunk owns a VBO and an IBO. When chunk is being updated, the blocks' face data is generated from block info, and is re-uploaded to the VBO and IBO, by its nature, the size is dynamic.

However that I see that currently both `VertexBuffer` and `IndexBuffer`'s `write` method both asserts that the size written is same with the size used to initialize the buffer, which makes this goal unable to achieve. It seems like a common operation (With raw GLAPI it's as simple as calling `glBufferData` again), but I didn't find anything relevant to this in documentation/examples.

**Comment by tomaka** [comment]
It was decided to not allow resizing buffers, because it's less error-prone and to allow glium to use glBufferStorage instead of glBufferData.
If you want to rewrite the content of the whole buffer, you can just create a new buffer.

**Comment by WeAthFoLD** [comment]
I see, fix-sized buffers do have more pros than cons. Just curious: Will it be slower if we create new buffers every time and discard old ones, or the difference is negligible?

**Comment by tomaka** [comment]
The difference should be around 5-10µs per frame.

**Comment by WeAthFoLD** [comment]
Okay, thank you!
