### ISSUE TITLE
SEGV on OS X 10.10 with example app from tutorial

### ISSUE THREAD

**Issue by chancancode** [tomaka/glium#1486]
> error: Process didn't exit successfully: `target/debug/universe` (signal: 11, SIGSEGV: invalid memory reference)

The code is mostly based on the tutorial. I collected the `main.rs`, `Cargo.lock` and the crash dump here: https://gist.github.com/chancancode/789e70d1b482db403d43798a739c9642

**Comment by chancancode** [comment]
To be clear, the crash happens when you close the window

**Comment by tomaka** [comment]
That seems to be a glutin issue, not a glium issue. You should open an issue in glutin.
