### ISSUE TITLE
simple way to store an uniforms.

### ISSUE THREAD

**Issue by tioover** [tomaka/glium#1490]
I want create uniforms in a function and store it in other function, this is difficult.

If generate a uniforms with `uniforms!`, this type is complex and difficult to get, Rust haven't `decltype `.

And can't use trait object. because `Uniforms` trait isn't object-safe.

Unless, define a new struct

```rust
struct Foo {...}

impl Uniforms for Foo {...}
```

But `visit_values` function is too trivial and repeat, I trie write [a macro](https://github.com/tioover/rier/blob/master/src/shader.rs#L38),  that can implement the type that haven't lifetime, look like implement a trait with lifetime beyond the capability of the rust macro system.

```rust

macro_rules! implement_uniforms
{
    ($name: ident, $($field: ident),*) =>
    {
        impl $crate::glium::uniforms::Uniforms for $name {
            fn visit_values<'a, F>(&'a self, mut output: F)
                where F: FnMut(&str, $crate::glium::uniforms::UniformValue<'a>)
            {
                use $crate::glium::uniforms::AsUniformValue;
                $(
                    output(stringify!($field), self.$field.as_uniform_value());
                )*
            }
        }
    }
}
```

**Comment by quadrupleslap** [comment]
Uh, what happened here?

**Comment by tioover** [comment]
@quadrupleslap I was directly implemented the `Uniforms` trait.
