### ISSUE TITLE
`GlutinFacade::draw()` blocks when waiting for events in another thread

### ISSUE THREAD

**Issue by spearman** [tomaka/glium#1518]
Trying to wait for events in another thread seems to cause the rendering thread to block when calling `GlutinFacade::draw()`

Technically I think it is 'unsafe' to use OpenGL multi-threaded in this manner, but it supposedly "should work" on most platforms. For example, this works using `glutin` windows:

```
extern crate glium;
use glium::glutin;

fn main () {
  let input_window = glutin::WindowBuilder::new()
    .with_visibility(false)
    .build().unwrap();

  let input_thread  = std::thread::current();
  let _ = std::thread::spawn (
    move || {
      let render_window = glutin::WindowBuilder::new()
        .with_vsync()
        .build().unwrap();

      unsafe { render_window.make_current().unwrap() };

      input_thread.unpark();

      let mut frame = 0;
      'frameloop: loop {
        if frame % 60 == 0 {
          println!("frame: {}", frame);
        }

        render_window.swap_buffers().unwrap();

        frame += 1;
      }
    }
  );

  std::thread::park();

  'inputloop: for event in input_window.wait_events() {
      println!("{:?}", event);
  }
}
```

The inputloop proceeds to receive events asynchronously and the rendering thread swaps buffers on vsync.

Here's essentially the same program using a `GlutinFacade`:

```
extern crate glium;
use glium::glutin;
use glium::{
  DisplayBuild,
  Surface};

fn main () {
  let input_window = glutin::WindowBuilder::new()
    .with_visibility(false)
    .build().unwrap();

  let input_thread  = std::thread::current();
  let _ = std::thread::spawn (
    move || {
      let render_facade = glutin::WindowBuilder::new()
        .with_vsync()
        .build_glium().unwrap();

      unsafe {
        render_facade.get_window().unwrap().make_current().unwrap()
      };

      input_thread.unpark();

      let mut frame = 0;
      'frameloop: loop {
        if frame % 60 == 0 {
          println!("frame: {}", frame);
        }

        let mut glium_frame = render_facade.draw(); // blocks here
        glium_frame.clear_all ((0.0, 0.0, 1.0, 1.0), 0.0, 0);
        glium_frame.finish().unwrap();

        frame += 1;
      }
    }
  );

  std::thread::park();

  'inputloop: for event in input_window.wait_events() {
      println!("{:?}", event);
  }
}
```

The inputloop still processes events, but the frameloop blocks on the line `let mut glium_frame = render_facade.draw();` although I haven't found exactly why. In the source code it seems to be calling `Frame::new()` which gets the framebuffer dimensions and clones the `Rc<Context>` in the backend, neither of which I expect to be 'blocking' operations.

Tried setting current on the backend Window as well but haven't gotten it to work. I would *really* like to de-couple input from rendering, which seems possible, maybe with some unsafe methods, and still be able to use high-level `glium` surface rendering.

**Comment by tomaka** [comment]
> Technically I think it is 'unsafe' to use OpenGL multi-threaded in this manner, but it supposedly "should work" on most platforms.

That's not true. On at least my Linux machine it doesn't work.

**Comment by spearman** [comment]
You can probably close this issue, for reference here are a couple threads on the topic:

https://www.opengl.org/discussion_boards/showthread.php/164775-renderer-in-separate-thread

https://www.opengl.org/discussion_boards/showthread.php/182226-SwapBuffers%28%29-in-another-thread

https://www.opengl.org/wiki/OpenGL_and_multithreading

There didn't seem to be an easy way to set glx/wglContext(NULL,NULL) on the original thread with the exposed glutin interface, so I ended up using an SDL backend since it was easier to "cheat" and duplicate the SDL "context" on a separate thread, then use the SDL event pump on the original thread.
