### ISSUE TITLE
tutorials-08-14 still at level 140 and using inverse

### ISSUE THREAD

**Issue by buzmeg** [tomaka/glium#1524]
I reported this about tutorial-08 a couple months ago (Reference: https://github.com/tomaka/glium/issues/1432).  Shaders are flagging #version 140 but inverse requires #version 150.

If glium has been deprecated by vulkano (I note that commits have dropped, last commit is a month ago, reported bugs are not getting fixed), please do at least let the community know that you have abandoned glium and that we should not use it anymore.

Thanks.

**Comment by nicokoch** [comment]
> If glium has been deprecated by vulkano (I note that commits have dropped, last commit is a month ago, reported bugs are not getting fixed), please do at least let the community know that you have abandoned glium and that we should not use it anymore.

Well, he did. So you should've at least checked before making your accusations...
https://users.rust-lang.org/t/glium-post-mortem/7063

**Comment by tomaka** [comment]
It's not *really* deprecated, it just needs a big rework which I don't have time for.

**Comment by buzmeg** [comment]
I did search for both "glium deprecated" and "glium abandoned" on Google.  That post doesn't even pop up on Google unless I search very specifically for "glium post-mortem".  And even *THAT* doesn't pop up on other search engines (presumably the post is too new as of this date).

In addition, I would expect such important information as is contained in https://users.rust-lang.org/t/glium-post-mortem/7063 to be contained in the README.md where *everybody* can find it rather than having to very specifically craft a search to find it.

Finally, just because the owner has decreased his contributions does not automatically mean something should not be used.  The library could be in the middle of a handoff or it could be "complete".  The fact that neither are the case should probably be marked.

I'm glad tomaka did this work, and I'm sure the things he learned will make the work he does on Volkano much stronger.  I fully appreciate the demands a library like this makes on your time as I have been in his position for a much smaller, less visible group of people.  OpenGL drivers being a pile of flaming dog poo makes the experience even less pleasant.

However, partially-complete, zombie libraries are a social problem in that they will socially drown out something better (ask the Lisp guys about this).  Something like glium that got a lot of coverage and *sorta* works will be a particular obstacle.

Set a date to put a knife through it (I would suggest about 3 months in the future--long enough to give people a chance to react but not so long that they consider it too low priority) and follow through.  This also has the advantage of causing someone reliant on the library to finally step up to take it over.  And, if nobody does step up, well, that's a statement, too.

Thanks for the work.  I'll be heading to go get a Vulkan/Vulkano system to set up.

Bug closed.
