### ISSUE TITLE
Question: Will glium support webassembly?

### ISSUE THREAD

**Issue by casey** [tomaka/glium#1539]
I'm trying to pick a graphics library to learn so that I can eventually write graphics apps in rust which can be compiled to webassembly and render with WebGL.

Is this something that glium will support? Not looking for a hard promise or anything, since the future is uncertain, just like probably or probably not.

Thanks a bunch!

**Comment by tomaka** [comment]
Glium should support WebGL already.

As far as I know, it is not possible yet to use WebGL with Webassembly. But when it becomes possible, the changes to make to glium will most likely be minimal.

**Comment by casey** [comment]
Sweet, thanks for the answer!
