### ISSUE TITLE
BackendCreationError(OsError("CreateWindowEx function failed: Invalid access to memory location. (os error 998)"))

### ISSUE THREAD

**Issue by dten** [tomaka/glium#1546]
BackendCreationError(OsError("CreateWindowEx function failed: Invalid access to memory location. (os error 998)"))
I'm getting this error but only with `--release`
```
let b = glutin::WindowBuilder::new();
let display = b.build_glium()
               .expect("build_glium err");
```

edit:
have found it has an error when using `stable-x86_64-pc-windows-gnu` but works fine when using `stable-i686-pc-windows-gnu`

this is using glium 0.15

**Comment by tomaka** [comment]
Please open an issue in glutin instead: https://github.com/tomaka/glutin
