### ISSUE TITLE
clear is very slow

### ISSUE THREAD

**Issue by tmsbrg** [tomaka/glium#1551]
Just made a basic project, and noticed it was very slow (11 ms per frame, only drawing a single triangle). I went to investigate the cause and found, to my surprise, that my call to frame.clear_color was using up 90% of the time in each frame.

Some of the output from my basic measurements (press space while playing the basic project to view this):
```
clear time:   9.3265 ms
frame time:  10.0298 ms

clear time:  10.8911 ms
frame time:  11.5724 ms

clear time:  10.3683 ms
frame time:  11.6192 ms
```
Looking at the implementation for clear I can see why it's much slower than I expected:
https://github.com/tomaka/glium/blob/master/src/ops/clear.rs
Why is there so much state switching going on in there? It seems like changing state is avoided in draw calls but not in clear calls. It's hard for me to see what's necessary and what's not. Is there a way you could remove the unnecessary work for clear?

My project's source code:
[basic-project.tar.gz](https://github.com/tomaka/glium/files/635147/basic-project.tar.gz)

**Comment by tomaka** [comment]
> Why is there so much state switching going on in there? It seems like changing state is avoided in draw calls but not in clear calls. It's hard for me to see what's necessary and what's not. Is there a way you could remove the unnecessary work for clear?

There's no "unnecessary work". The state switches are indeed avoided with the `if`s.

The answer is most likely driver magic. You maybe have vsync activated and for some reason the driver waits for vsync at the start of the frame instead of when swapping buffers.

**Comment by tmsbrg** [comment]
I did some more testing and I think you're right. I first tried to simply remove the clear and still got slow speeds. Then I tried using only glutin and gl, and only clearing the screen with `unsafe { gl::Clear(gl::COLOR_BUFFER_BIT) };`. Doing that resulted in frame time still being around 11 ms with clearing time (that one function call) taking up 90% of the time (so exactly like with the glium clear function).

I guess it makes sense to have vsync kick in at the start of the next graphics call rather than the buffer swap, as that would give the CPU time to do stuff while the GPU is drawing. I didn't know a basic draw took 11 ms though, I thought it'd only get that slow if I actually drew a lot of stuff. I don't have that bad a GPU either. I should do some tests to see how fast it is when drawing a whole lot of stuff.

Anyway thanks and sorry for wasting your time. I guess it's not glium's fault after all.

**Comment by tmsbrg** [comment]
Did some additional testing, including drawing 4'000'000 triangles in a single draw call and 80'000 in 50 draw calls. Also added a 10 ms sleep before drawing to simulate high CPU activity. Still got good enough speeds for 60 FPS (<= 16 ms). So yay, it's good!

Thanks for making this, Tomaka. Glium's a lot nicer to work with than raw OpenGL.
