### ISSUE TITLE
Implement all the blending operations

### ISSUE THREAD

**Issue by tomaka** [tomaka/glium#161]

**Comment by bvssvni** [comment]
Could add a struct `Blend`:

```Rust
pub struct Blend {
    pub color: BlendingFunction,
    pub alpha: BlendingFunction,
    pub color: (f32, f32, f32, f32),
}

impl Default for Blend {
     fn default() -> Self {
        Blend {
            color: BlendingFunction::Addition {
                source: LinearBlendingFactor::SourceAlpha,
                destination: LinearBlendingFactor::OneMinusSourceAlpha,
            },
            alpha: BlendingFunction::Addition {
                source: LinearBlendingFactor::One,
                destination: LinearBlendingFactor::One,
            },
            color: (1.0, 1.0, 1.0, 1.0),
        }
    }
}
```

This will make alpha blending become enabled by default if `DrawParameters::blend` is set to `Some(Default::default())`.

Then replace `DrawParameters::blending_function` with

```Rust
pub blend: Option<Blend>
```

**Comment by bvssvni** [comment]
Add the following to `LinearBlendingFactor`:

```Rust
SourceAlphaSaturated,
ConstColor,
ConstAlpha
OneMinusConstColor,
OneMinusConstAlpha,
```

**Comment by tomaka** [comment]
I don't think `Default` should be implemented for the blending function.
Sure the regular alpha blending is what most people will do, but it's also too magical.

Having a `Blend` struct is not a bad idea though.

**Comment by bvssvni** [comment]
Ok, so no default?

**Comment by tomaka** [comment]
Yeah, no `Default`.

I think that a `Blend::alpha_blending()` method would be nice though.

**Comment by bvssvni** [comment]
I'll make a PR.

**Comment by bvssvni** [comment]
- [ ] Add struct `Blend`
- [ ] Derive `Clone, Debug, PartialEq` for `Blend`
- [ ] Move over doc comment from `BlendFunction` to `Blend` (and fix to reflect the new API)
- [ ] Add `Blend::alpha_blending`

**Comment by bvssvni** [comment]
I've talked to @tomaka about https://github.com/tomaka/glium/issues/1208 and we decided to remove the `Option` to get rid of the "don't care" state, which might lead to confusion.
