### ISSUE TITLE
Implement primitive restart index

### ISSUE THREAD

**Issue by tomaka** [tomaka/glium#180]
Low priority.

**Comment by tomaka** [comment]
For compatibility with GL ES 3, only fixed restart index will be supported.

Glium will automatically call `glPrimitiveRestartIndex` with the right value if `GL_PRIMITIVE_RESTART_FIXED_INDEX` is not supported.

**Comment by sharazam** [comment]
Any update on this? The only way to draw multiple objects using the same shader in one draw call right now is to use an index buffer with MultidrawElement - which is only available on OpenGL 4 and up iirc.

Restart index is supported on older hardware. What function do you have to call to restart the index (for beginning a new object in the same VBO)?

**Comment by sharazam** [comment]
There hasn't been done anything. I need this to work on OGL 3.3 where MultiDraw isn't available. My proposal is to add this to the DrawParameters struct. Assigning to self.
