### ISSUE TITLE
Switching from debug to release changes what gets drawn.

### ISSUE THREAD

**Issue by TyOverby** [tomaka/glium#208]
# With Debug
![out](https://cloud.githubusercontent.com/assets/573215/5602448/be3bff3a-9302-11e4-954d-c5d94664ceca.gif)

# With Release
![out](https://cloud.githubusercontent.com/assets/573215/5602452/e947ee5a-9302-11e4-9da0-7f422b080f1d.gif)

I have no idea what is causing this, but what I think might be part of the issue is that I'm making a vertex buffer, drawing it, and then throwing it away immediately after drawing it.  Could there be a race condition here?

**Comment by TyOverby** [comment]
trace: https://dl.dropboxusercontent.com/u/14007801/lux_demo.trace

**Comment by tomaka** [comment]
May have been fixed by https://github.com/tomaka/glium/pull/209

**Comment by TyOverby** [comment]
It looks like 209 did indeed fix it!  So it was actually a multithreaded race condition?  Why is glium multithreaded in this way?

**Comment by tomaka** [comment]
Technically it was not a race condition. I was sending a pointer to a buffer in another thread, and the buffer was reused before the other thread had finished reading it. More an ownership problem.

The reason why glium is multithreaded is to guarantee safety. I'm thinking of allowing the user to manage threading himself, but that would be with unsafe code.
