### ISSUE TITLE
Why does frame need to have the same lifetime as the Display that spawned it?

### ISSUE THREAD

**Issue by TyOverby** [tomaka/glium#215]
It makes a copy of the display to store inside itself, so it seems like the only purpose would be to keep you from performing operations on your original display.

**Comment by tomaka** [comment]
The idea was to prevent the user from screwing up.

Imagine this:

```rust
let frame1 = display.draw();
let frame2 = display.draw();

frame1.draw(...);
frame2.draw(...);
```

I'm not too sure about this design.
As you said there's no technical limitation, but semantically it makes no sense to draw two frames simultanously.

**Comment by TyOverby** [comment]
Yeah... With the clone in place it seems like an arbitrary restriction.  In my case, I want my library to allow users to perform operations (like event handling) while they have a frame open.

My vote would be to remove this restriction and either document the case very well, or fail when two frames are open at the same time.

**Comment by TyOverby** [comment]
Could we revisit this?  I'm having to jump through hoops to work around the borrow issues.
