### ISSUE TITLE
Add alternative to #[vertex] for Rust 1.0 compatibility

### ISSUE THREAD

**Issue by tomaka** [tomaka/glium#233]

**Comment by TyOverby** [comment]
Why is an alternative needed?

**Comment by tomaka** [comment]
`glium_macros` is a plugin and macros will be disabled in 1.0 stable.

**Comment by TyOverby** [comment]
They will still be available with an `#[allow]` directive right?

**Comment by cmr** [comment]
No, no plugins are allowed for the stable channel.

On Fri, Jan 9, 2015 at 8:57 PM, Ty <notifications@github.com> wrote:

> They will still be available with an #[allow] directive right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomaka/glium/issues/233#issuecomment-69433078>.
>



-- 
http://octayn.net/

**Comment by TyOverby** [comment]
So every macro that isn't a `macro_rules` is getting canned?  With how popular those have been for the last few months, this seems like a huge mistake.
