### ISSUE TITLE
type `glutin::WindowBuilder<'_>` does not implement any method in scope named `build_glium`

### ISSUE THREAD

**Issue by THeK3nger** [tomaka/glium#255]
I was trying to compile the triangle.rs example but I've got the error in the title

    type `glutin::WindowBuilder<'_>` does not implement any method in scope named `build_glium`

**Comment by tomaka** [comment]
Make sure you have `use glium::Surface;` somewhere in your code. That's where `build_glium` is defined.

**Comment by THeK3nger** [comment]
Ok. That code (`use glium::DisplayBuild;`) was present. The problem was that in my Cargo.toml I was mixing glium from GitHub with glutin from crates.io. Using the GitHub version of glutin fixed the problem.

**Comment by tomaka** [comment]
Oh. Good to know that it causes problems, I wasn't aware of that!

**Comment by stephanstross** [comment]
I'm still getting this error, and both glium and glutin are on the github version.
