### ISSUE TITLE
Match GL stack over- and underflow errors

### ISSUE THREAD

**Issue by camjackson** [tomaka/glium#268]
In going through all of the docs, I noticed [this commented out code](https://github.com/tomaka/glium/blob/ea9b5894afb6748df721480e64edb6127cf4d608/src/lib.rs#L1499). Is there a reason it's commented out, and not either active or just deleted?

**Comment by tomaka** [comment]
The reason is that at that time I was only using OpenGL3, and the `STACK_UNDERFLOW` and `STACK_OVERFLOW` constants appeared in OpenGL4 (gl_generator is very strict about versions).
