### ISSUE TITLE
Add documentation for vertex_array_object

### ISSUE THREAD

**Issue by camjackson** [tomaka/glium#270]
There are no docs here: https://github.com/tomaka/glium/blob/master/src/vertex_array_object.rs

I only bother to raise this as an issue because all the other files directly in `src` have pretty good docs, and there are a few empty `///`s in this one, just begging for some explanation :P

I'd add it myself but I'm pretty new to glium, and OpenGL in general.

**Comment by tomaka** [comment]
This is low priority since vertex_array_object is private
