### ISSUE TITLE
Replace #[uniforms] by uniform! everywhere

### ISSUE THREAD

**Issue by tomaka** [tomaka/glium#272]
Note that `#[uniforms]` is not deprecated. However glium itself won't use it in order to be compatible with stable Rust 1.0.

**Comment by davekong** [comment]
The [example][1] in the documentation is broken without using the uniform! macro because matrix does not implement the Copy trait (according to rustc).

[1]: http://tomaka.github.io/glium/glium/index.html#complete-example

```
src/main.rs:19:1: 19:12 error: the trait `Copy` may not be implemented for this type; field `matrix` does not implement `Copy` [E0204]
src/main.rs:19 #[uniforms]
```

**Comment by davekong** [comment]
Ack, sorry, I seem to have made a typo that caused this.

**Comment by tomaka** [comment]
Done
