### ISSUE TITLE
Need to support glBlendFunc(GL_ONE, GL_ONE); for deferred rendering example.

### ISSUE THREAD

**Issue by palodequeso** [tomaka/glium#301]
In order to do the additive blending when iterating over the scene's lights and rendering to the light FBO, I need to be able to specify a blending function of glBlendFunc(GL_ONE, GL_ONE); Currently that is not an option.

**Comment by tomaka** [comment]
Fixed by #303

**Comment by palodequeso** [comment]
Thanks, I should be able to finish this example up today now.
