### ISSUE TITLE
Provide event iterator

### ISSUE THREAD

**Issue by aepsil0n** [tomaka/glium#325]
`DisplayBuild::poll_events` returns a `Vec` but I think it should be an iterator, ideally an infinite one, see also tomaka/glutin#212.

**Comment by tomaka** [comment]
Are you working on this? I'm thinking of reworking the interaction between glium and its backend, which may solve this.

**Comment by aepsil0n** [comment]
I have been, but I ran into an issue. Let me open a PR to discuss it…

**Comment by aepsil0n** [comment]
Wait, if you want to rework it entirely, this is irrelevant.

[My attempt to solve this](https://github.com/aepsil0n/glium/tree/event-iter) did not work out. I tried to register iterators that own a receiver by creating new channels, but now the context thread has no way of aborting and keeps running in the background. I guess this could still be fixed, but it may not be worth it.

**Comment by tomaka** [comment]
I'm getting many design-related problems when rewriting the backend. I think I'm just going to fix this individual problem and rewrite it later.

**Comment by aepsil0n** [comment]
Yeah, ok, binding the iterator to the context's lifetime makes this a bit simpler. For some reason I tried to avoid that… Now that I think about there's no really good reason for it though.

Anyway, thanks for fixing this.

**Comment by aepsil0n** [comment]
Hm… for me the `EventIter` only receives the first poll before being exhausted. Patch incoming.
