### ISSUE TITLE
Allow reading and re-uploading compressed texture data

### ISSUE THREAD

**Issue by tomaka** [tomaka/glium#326]
It is possible with OpenGL to upload textures that are already compressed and to read compressed texture without decompressing them.

**Comment by thelink2012** [comment]
I'd give this issue a bit more of priority (i.e. adding it to the 1.0 milestone) given the fact uploading pre-compressed textures is a very common requirement and adding it in a _sane_ way would probably cause api breakage, so doing it pre-1.0 seems essential.

Same for pre-computed mipmaps, I see there's no open issue for that one?
