### ISSUE TITLE
Can the Texture types implement Eq?

### ISSUE THREAD

**Issue by TyOverby** [tomaka/glium#329]
Being able to compare two handles would be nice.

I'm requesting this because I end up wrapping textures in `Rc`, and once they've been wrapped, it's hard to tell if they are pointing to the same thing or not without some hacks.

**Comment by tomaka** [comment]
Wouldn't it be better for you to just cast the `Rc` into a `*const Texture2d`, and compare the pointers?
I don't think there are any type in the standard library that compare for equality by address. Since there can only be one `Texture*` object per texture, I feel like this would be a hack.

**Comment by TyOverby** [comment]
Yeah, sounds like I'll just do that.
