### ISSUE TITLE
question: what API would I use to create a display with window borders and use swap_buffers?

### ISSUE THREAD

**Issue by andrewrk** [tomaka/glium#346]
glium::Display struct has no `swap_buffers()` method. How would the triangle example be extended to:

 1. Use vsync and `swap_buffers()` instead of sleeping
 2. have a title bar and window borders like normal windows

**Comment by tomaka** [comment]
1 - `swap_buffers()` is automatically called when you [call `target.finish()`](https://github.com/tomaka/glium/blob/master/examples/triangle.rs#L96). However vsync doesn't really work correctly and I don't know why, but that's a problem with glutin.

2 - The window should have a title bar and borders. Which platform are you on? If this is not the case, also a problem with glutin :-/

**Comment by andrewrk** [comment]
I just ran the triangle example directly from glium's repository and it does in fact have window borders. So I must have made a mistake in my code.

So the sleep is a workaround for a bug in vsync, is that right?

**Comment by andrewrk** [comment]
When I use this example, it looks like vsync works: https://github.com/gfx-rs/gfx-rs/blob/master/examples/glutin/main.rs

btw my platform is Ubuntu 14.10.

**Comment by tomaka** [comment]
> So the sleep is a workaround for a bug in vsync, is that right?

Yes

> When I use this example, it looks like vsync works: https://github.com/gfx-rs/gfx-rs/blob/master/examples/glutin/main.rs

Vsync isn't even implemented in glutin on Linux. Your system may automatically enable vsync, but on my system when I remove the sleep the application starts consuming a lot of CPU.

**Comment by andrewrk** [comment]
It looks like using vsync in windowed mode is buggy. I tried it with GLFW. So I think my application will have vsync off and use sleep() to go easy on the CPU.
