### ISSUE TITLE
Implement compute shaders

### ISSUE THREAD

**Issue by tomaka** [tomaka/glium#354]

**Comment by tomaka** [comment]
Suggested API:

- Add `ComputeShader`, totally separated from `Program` but which uses the same API.
- Add `ComputeShader::execute(U) where U: Uniforms`

Performance issue: in regular OpenGL apps you can have a compute shader inside a program, which may avoid some calls to `glUseProgram` when compared to this API proposal.
This could be fixed later by adding a `ProgramWithComputeShader` type for the people who want to optimize every tiny little bit.

**Comment by tomaka** [comment]
Note that this probably won't be done before images loading/storing or SSBOs are implemented, because compute shaders are pretty useless without these

**Comment by palodequeso** [comment]
This is an awesome idea!

**Comment by chwevans** [comment]
Any updates on when this will happen?

**Comment by tomaka** [comment]
Compute shaders aren't difficult to implement, but it would be pointless to add them before #362 or #361, and they both depend on #945
