### ISSUE TITLE
remove cgmath support

### ISSUE THREAD

**Issue by andrewrk** [tomaka/glium#364]
cgmath is deprecated: https://github.com/bjz/cgmath-rs/issues/144

Removing support in favor of nalgebra will lead to a less confusing API.

**Comment by tomaka** [comment]
I don't think the API is confusing. The only place where cgmath is used is here: https://github.com/tomaka/glium/blob/9ecf57c01096e3b18cd1cc568534f353781329a6/src/uniforms/value.rs#L500-552
