### ISSUE TITLE
Missing field in macros/src/vertex.rs

### ISSUE THREAD

**Issue by drmugg123** [tomaka/glium#399]
latest rust nightly(rustc 1.0.0-nightly (92ff8ea52 2015-01-27 23:08:13 +0000)) complains about the field 'associated_types' missing from the vertex macro definiton at line 14.

**Comment by drmugg123** [comment]
i would do a pull request and do it myself, but i'm not familiar enough with git. sorry

**Comment by tomaka** [comment]
Fixed in #400
