### ISSUE TITLE
On a Retina Mac, the viewport rect is incorrect and the window stops responding after a few seconds

### ISSUE THREAD

**Issue by dylanede** [tomaka/glium#401]
I've just checked out glium and glutin, and tweaked it to work with the latest rust by changing `io` to `old_io`. Glutin's examples all work fine, as far as I can tell, but Glium's examples all stop responding (the window becomes greyed-out and the cursor becomes a timer, though rendering continues to update, as proved by the blitting example) after a few seconds. As well as this, the viewport rectangle seems to be confused by the High DPI display. It seems as if the viewport has width and height in HDPI pixels equivalent to the LDPI width and height of the window, with its origin in the bottom left of the window. As a result the rendered region is shrunk down into the bottom left corner, with the rest of the window being blank.

**Comment by TyOverby** [comment]
I'm getting the exact same issues on my end as well.

**Comment by simnalamburt** [comment]
It happens same in MacBook Air (13-inch, Mid 2011), `OS X 10.10.2`

**Comment by dylanede** [comment]
I think this issue can be closed now, as the examples seem to behave correctly on OS X 10.10 (however there are other issues with earlier versions of OS X, such as 10.8).
