### ISSUE TITLE
Unable to render texture correctly

### ISSUE THREAD

**Issue by drmugg123** [tomaka/glium#409]
trying to render a .png to a quad but it's either just black or just white. it seems strange since i can't see anything wrong in my code. i'm perfectly able to render anything other than a texture if i write the colours myself in the fragment shader.

this is the texture i'm trying to render:
https://raw.githubusercontent.com/tomaka/glium/master/tests/fixture/opengl.png

this is my code:
https://gist.github.com/drmugg123/2867f2938dc525f88042

this is my system information:
https://gist.github.com/drmugg123/51f16d6aa419fbd86919

**Comment by drmugg123** [comment]
oh and here's a trace from apitrace that shows that the texture is bound in OpenGL correctly:
http://s000.tinyupload.com/index.php?file_id=06108563672219143495

**Comment by tomaka** [comment]
I merged this one hour ago: https://github.com/tomaka/glium/pull/408

Could you try updating glium and check if it works?

**Comment by drmugg123** [comment]
it works! but i get slight artifacts for some reason. here's a picture:
http://i.imgur.com/0z0gkxV.png

**Comment by tomaka** [comment]
Hmm, that's very weird. Could you try replacing `CompressedTexture2d` by `Texture2d` and see if it works?

Changing the sampling method is a bit clumbsy for the moment. You can't do it with a `Uniforms` struct, but you can with the `uniform!` macro:

Replace:

```rust
let uniforms = Uniforms {
    sampler: &texture,
}; 
```

By:

```rust
let uniforms = uniform! {
    sampler: glium::uniforms::Sampler(&texture, glium::uniforms::SamplerBehavior {
        // insert options here
        .. std::default::Default::default()
    })
}; 
```

See the documentation of the `SamplerBehavior` struct here: http://tomaka.github.io/glium/glium/uniforms/struct.SamplerBehavior.html

**Comment by drmugg123** [comment]
yep, changing it from CompressedTexture2d to Texture2d removes the artifacts.
