### ISSUE TITLE
NAlgebra support isn't working with my setup

### ISSUE THREAD

**Issue by adudney** [tomaka/glium#424]
I'm assuming I just don't know how features work.

Code here: (Including part of Cargo.toml)

https://gist.github.com/adudney/46cb7842dcaeb061ebd6

**Comment by tomaka** [comment]
It's because glium uses the version of nalgebra coming from github, while you use the version coming from crates.io
Rust thinks that they are two totally different crates.

**Comment by adudney** [comment]
Hm. Interesting, thanks, I've tested it and that works great.
