### ISSUE TITLE
Allow non float vertex attributes

### ISSUE THREAD

**Issue by jfooh** [tomaka/glium#431]
The test in vertex_array_object.rs:46 seems only to allow using float values for vertex attributes:
Using a vertex like
```
#[vertex_format]
#[derive(Copy)]
struct Vertex {
    a_pos: [i16; 2],
    a_color: [u8; 4],
    a_tex: [i16; 2],
}
```
with this fragment shader
```
attribute vec2 a_pos;
attribute vec2 a_tex;
uniform mat4 mvp;
varying vec2 v_tex;
void main() {
v_tex = (a_tex / 256.0);
gl_Position = mvp * vec4(a_pos / 4.0, 0.0, 1.0);
}
```
results in: thread '<main>' panicked at 'The program attribute `a_pos` does not match the vertex format'

Instead of just using GL_SHORT as type for  glVertexAttribPointer :)

**Comment by tomaka** [comment]
It should work if you write `attribute ivec2 a_pos` in your shader.

**Comment by tomaka** [comment]
But yes, it should be possible to turn non-floats into floats.

**Comment by jfooh** [comment]
that should work - though I have almost exclusively worked with gles2 so far which does not have the option to use ivec for vertex attributes in the fragment shader   

gfx-rs has an #[as_float] to mark vertex attributes in the struct btw

**Comment by jfooh** [comment]
hm no, even on desktop ivec is not available here  (should be a GL 3.2 context)
```
thread 'glium rendering thread' panicked at 'Debug message with high or medium severity: `0:3(1): error: vertex shader input / attribute cannot have type `ivec2'
```

**Comment by tomaka** [comment]
Hmm, that's probably because old GLSL versions don't support it.

**Comment by jfooh** [comment]
indeed, with shader version 120 ivec input is accepted

**Comment by jfooh** [comment]
One piece is missing at line vertex_array_object:150 I guess. It should select the VertexAttribPointer version (also) depending on the shader attributes.

**Comment by tomaka** [comment]
I already fixed it in #432, just waiting for travis to pass before merging.

**Comment by jfooh** [comment]
I meant one needs to decide depending on whether attribute.ty is a float or int type if VertexAttribPointer or VertexAttribIPointer is used. (gles2 has no VertexAttribIPointer iirc)

**Comment by tomaka** [comment]
Oh, I thought I was doing what you were suggesting.

**Comment by tomaka** [comment]
Should be fixed in #437

**Comment by tomaka** [comment]
Thanks for taking a closer look at this! You probably avoided a future problem with GLES 2.

**Comment by jfooh** [comment]
fix-attribs works nicely - Thank you!
