### ISSUE TITLE
Need a draw parameter for enabling glDepthMask.

### ISSUE THREAD

**Issue by palodequeso** [tomaka/glium#433]
This is pretty straight forward, if the parameter is true, then just add the state glDepthMask(GL_TRUE); to the OpenGL state stack. This allows one to do things like, render a scene in a deferred manner, but still render translucent or non-lit objects in a forward manner and combine the results without any extra shader magic.

**Comment by tomaka** [comment]
I'm in favor of modifying `DepthFunction` instead of adding a field to `DrawParameters`, would this make sense?

**Comment by palodequeso** [comment]
Hmm, it would double the size of your depth function values, because it is a separate piece of state from what I understand. It is not the same as enabling the depth test.

**Comment by tomaka** [comment]
I got confused because of the verification that a depth buffer is present, but it should be easy to make it correct.

**Comment by palodequeso** [comment]
No worries.

**Comment by tomaka** [comment]
Actually there's a legitimate problem: what should the default value of `depth_mask` be?

If I set the default to `true`, then you need to have a depth buffer by default or an `Err` is generated. That would mean that `texture.as_surface().draw()` requires you to pass draw parameters with `depth_mask` set to `false`.

I could also set the default to false, but then people may get lots of confusing problems.

**Comment by palodequeso** [comment]
According to this I think the default is true, but that seems odd.  http://www.glprogramming.com/blue/ch05.html#id31383

**Comment by kvark** [comment]
@tomaka 
> If I set the default to true, then you need to have a depth buffer by default or an Err is generated.

It doesn't make much sense to write (or even test) depth if there is no depth buffer attached, but I don't think it's a GL error. For instance, the depth test behavior is clearly defined in the spec:

> if there is no depth buffer, it is as if the depth buffer test always passes

So the question is whether or not you want to provide a different (safer) semantics over what OpenGL does.

**Comment by tomaka** [comment]
@kvark Choosing a depth test other than `AlwaysReplace` generates an error in glium if no depth buffer is present.

I think that this is a good design (it prevents accidental mistakes) and I'd like to have something similar for the depth mask.

**Comment by kvark** [comment]
You probably meant `AlwaysPass`, but I get the idea ;)

**Comment by tomaka** [comment]
To bump this, I'd be in favor of setting adding `depth_write` to the draw parameters, and set the default value to `false`. Also add warnings a bit everywhere in the docs that you need to set this to true.

It should become a habit when you want depth testing to set both `depth_function` and `depth_write` in the parameters.

**Comment by tomaka** [comment]
Also, rename `depth_function` to `depth_test`, both for correctness and to explicitely break existing code that uses depth testing so that they add `depth_write`.
