### ISSUE TITLE
Two calls to Texture2d::new return the same texture

### ISSUE THREAD

**Issue by TyOverby** [tomaka/glium#520]
I'm calling Texture2d::new twice in quick succession with different images.  However, when I display them, both images are displayed exactly the same!

More interestingly, they have different GL ID numbers and have different dimensions.

**Comment by tomaka** [comment]
Ouch. It's more likely a problem when drawing instead of a problem when creating the textures.

Do you have an example code?

**Comment by TyOverby** [comment]
I'm a moron.  I had a caching layer in my graphics stack that I wasn't clearing properly.  

Sorry for any alarm!
