### ISSUE TITLE
Consider creating a "glium" organization

### ISSUE THREAD

**Issue by tomaka** [tomaka/glium#532]
I don't want to give the impression this is _my_ project and only _mine_, so a "glium" github organization is maybe better.

On the other hand, I don't see it as absolutely necessary.

**Comment by palodequeso** [comment]
Well, I will say on the extraordinarily rare occurrence that you're not around to fix something that broke with the nightly, it would be nice to have a small group of people that can also fix things.

**Comment by TyOverby** [comment]
Would this organization also own Glutin?

**Comment by tomaka** [comment]
@palodequeso Right. My personal rule is to grant the collaborator status to all people who have contributed to the core of the library. Once people are collaborators, I encourage them to also review and merge PRs.

I've received some fixes in the documentation, updates for rust, and your deferred shading example, but no-one has modified anything in the actual behavior of glium yet.
I'm thinking of being a bit more loose for glium, because I don't see as too good to have a "big" project with only one person.

@TyOverby That's a good question. I don't want to give the impression that glutin becomes tied to glium, they should remain totally independant. On the other hand it's hard to justify creating an organization for glium and not for glutin. But I don't want to create an organization for glutin.

**Comment by casey** [comment]
I just read [the glium post mortem](https://users.rust-lang.org/t/glium-post-mortem/7063/10), and I think that this might be a good idea.

If this repo was transferred to a organization account, people would be less likely to annoy you with questions.

Also, the move would be a good opportunity to make clear that although contributors might review and merge PRs, or occasionally implement new features, the project is abandoned, practically speaking, and is looking for maintainers.

**Comment by jhasse** [comment]
What should be the organization name? https://github.com/glium seems to be taken. https://github.com/rust-glium ?

**Comment by mitchmindtree** [comment]
Just thought I'd mention that I would be interested in being a part of an organisation along these lines if you are still considering the idea. Although my overall OpenGL knowledge is very limited, I will probably continue to contribute bug fixes and basic API updates (e.g. reflecting changes in winit) as I continue to use glium in my own projects. IMO glium is still the most thorough, accessible and idiomatic set of rust bindings to OpenGL that exist and I'll probably continue to use it until that is no longer the case (or if vulkan becomes accessible on macos, or if I happen to stop needing GUI in rust which I doubt will happen any time soon).

**Comment by bvssvni** [comment]
An organization could make it easier for people to write blogs, tutorials etc. I would like to see a group of people focusing on Glium, because OpenGL is still the most portable API out there. Currently I am forced to use raw OpenGL because a few bugs are blocking me on OSX in Glium and Gfx is still under heavy development.

Name suggestions for organization:

- RuGL (Rust + OpenGL)
- Rust-Open (various projects maintained by the Rust community)
- GliumDevelopers (like PistonDevelopers maintaining more than just Piston)

I was thinking a bit about moving Glutin to PistonDevelopers, but Piston might experiment with native window + UI backends in the future and this could make things confusing. The combination of Glium and Glutin is very popular and think it deserves its own organization.

**Comment by jhasse** [comment]
@tomaka Maybe you should just go ahead and create an org with any name you like. I don't think that the name is that important. This could really reduce the maintenance burden for you :)

**Comment by tomaka** [comment]
In fact I already own the glium organization.

**Comment by jhasse** [comment]
Oh that's awesome! Could you move tomaka/glium there? GitHub will set up redirects automatically IIRC.

**Comment by tomaka** [comment]
Well, let's go.

**Comment by a101010** [comment]
Very exciting trying to use the tutorial while you are moving. :)
Fortunately, markdown is still very readable, especially in github.

**Comment by Tom9729** [comment]
@a101010 tutorial is available [here](http://glium.github.io/glium/book).

**Comment by a101010** [comment]
Thanks!

**Comment by avl** [comment]
I really hope Glium will live on! It's a joy to work with, and OpenGL suits me perfectly for portability and performance. I'm already using it for my current big hobby project and don't really want to abandon that effort and port to Vulkan at this point.

If I can help I'm willing to invest some time in keeping Glium working as OS's, window managers and graphics drivers move around us.
