### ISSUE TITLE
Add possibility to add a marker in the GL queue

### ISSUE THREAD

**Issue by tomaka** [tomaka/glium#550]
...for easier debugging

https://www.opengl.org/registry/specs/GREMEDY/string_marker.txt
https://www.opengl.org/registry/specs/EXT/EXT_debug_marker.txt

**Comment by feliwir** [comment]
I think the implemented method for debug markers is suboptimal (and not working for me). Nowadays debug messages with `GL_DEBUG_TYPE_MARKER` should be used. Can this be reopened please?

See https://wikis.khronos.org/opengl/Debug_Output
