### ISSUE TITLE
Clarify design about shader versions

### ISSUE THREAD

**Issue by tomaka** [tomaka/glium#592]
This is problematic because old GLSL versions are not guaranteed to be supported in core OpenGL.

Should the user request the backend to support a specific version?
Should the user write multiple shaders for each possible version? In which case, should glium provide a way to choose the right one automatically?

**Comment by TyOverby** [comment]
>should glium provide a way to choose the right one automatically

This would be great.  Right now I have to choose between "this works on my desktop" and "this works on my macbook".
