### ISSUE TITLE
Change backend::Backend methods to take &mut self

### ISSUE THREAD

**Issue by nstoddard** [tomaka/glium#736]
I'm trying to use glium with `glfw-rs`. Several of its methods take `&mut self` instead of `&self`, which makes it difficult to implement the `backend::Backend` trait. The workaround is to use `transmute`:

```
unsafe impl backend::Backend for GlfwWindowBackend {
    fn swap_buffers(&self) {
        let self2: &mut GlfwWindowBackend = unsafe{mem::transmute(self)};
        self2.window.swap_buffers()
    }
    ...
```

This works, but it's ugly (is it also potentially unsafe?). I'd rather not have to use `transmute`. To fix this, several of the methods for `backend::Backend` need to be changed to take `&mut self`: `swap_buffers`, `get_proc_address`, and `make_current`.

**Comment by tomaka** [comment]
That should probably be changed in `glfw-rs`. There's no reason for these functions to take a `&mut self`.

Alternatively you could store a `RefCell<glfw::Window>` in your `GlfwWindowBackend` and call `self.window.borrow_mut().swap_buffers()` for example.

**Comment by Kerosene2000** [comment]
I think we have to talk about this, find an agreement :smile:
[Change Context::swap_buffers self ref mutability or not ? That's the question.](https://github.com/PistonDevelopers/glfw-rs/issues/340)

**Comment by Vtec234** [comment]
> There's no reason for these functions to take a `&mut self`.

When calling `get_proc_address` without a context, the function returns a null pointer. It does the same with a valid context for a function that the context does not support. So these two are to my best knowledge indistinguishable. It might therefore make sense to synchronise a call to `if !self.is_current() { self.make_current(); }` with the call to `self.get_proc_address(...);`, and without mutexes (mutices?) that can only be done with the mutability of the `self` reference. What do you think?
