### ISSUE TITLE
How to set global multisample? [not a issue]

### ISSUE THREAD

**Issue by tioover** [tomaka/glium#766]
sorry, I do not know where to ask questions...(some IRC?)

I just found [Texture Multisample](http://tomaka.github.io/glium/glium/texture/struct.Texture2dMultisample.html), there is something like:

    glfwWindowHint(GLFW_SAMPLES, 4);

**Comment by tomaka** [comment]
You can use `WindowBuilder().with_multisample(4).build_glium()` when creating the display.

To ask questions, you can try #rust-gamedev on irc.mozilla.org.
There's also the gitter, which I never advertised about but that I also follow: https://gitter.im/tomaka/glium

**Comment by tomaka** [comment]
And if you want to change it dynamically, you should create a new `WindowBuilder` and call `rebuild_glium`, like in the fullscreen example: https://github.com/tomaka/glium/blob/87b6dcaf1e19b57ebe4d4d9456327af77058c472/examples/fullscreen.rs#L115

**Comment by tioover** [comment]
Thank you!

**Comment by tioover** [comment]
I simply add `.with_multisampling(4)` in triangle, but

![image](http://ww2.sinaimg.cn/bmiddle/62c1e01egw1erep0u3g76j20dc0asq37.jpg)

**Comment by tomaka** [comment]
What's your platform?

**Comment by tioover** [comment]
OS X 10.10.3

**Comment by tomaka** [comment]
Multisampling hasn't been implemented for cocoa yet, sorry :(

Relevant issue: https://github.com/tomaka/glutin/issues/145

**Comment by tioover** [comment]
thank you agian
