### ISSUE TITLE
type `glutin::WindowBuilder<'_>` does not implement any method in scope named `build_glium`

### ISSUE THREAD

**Issue by stephanstross** [tomaka/glium#784]
IT'S BACK. I'm currently on the github versions of both glium and glutin, and glium::DisplayBuilder is in my code. Anyone have any ideas what's causing this issue?

**Comment by tomaka** [comment]
It doesn't matter if you use glium from github or from crates.io, but glutin must come from crates.io.

If you want to do some changes to glutin for example, you should use [Cargo's local overrides system](http://doc.crates.io/guide.html#overriding-dependencies) instead of using a github version.
