### ISSUE TITLE
Texture clobbering

### ISSUE THREAD

**Issue by TyOverby** [tomaka/glium#795]
I have a program that loads textures with Texture2d::new(), and in every time a new texture is loaded, the previous textures that were loaded get clobbered.

This only happens on one computer (that I have access to), so I don't have much information yet.  (I'll get apitraces tomorrow), but I do know that the texture id isn't being reused.

No opengl errors happen either

**Comment by tomaka** [comment]
:-/

This is maybe due to a bug while rendering, because of #783

**Comment by TyOverby** [comment]
I'm happy to say that this was an error in my own code!  I had refactored, and forgot to make changes to an older shader.
