### ISSUE TITLE
Message processing in tutorials doesn't work on OSX

### ISSUE THREAD

**Issue by camjackson** [tomaka/glium#831]
The 2 tutorials do:

    loop {
        //...
        if display.is_closed() {
            break;
        }
    }

On mac, this ends up with the spinning pin-wheel thing, and needing to press ctrl+c to kill the window.

If I change it to this instead:

    loop {
        //...
        for event in display.poll_events() {
            match event {
                glutin::Event::Closed => return,
                _ => ()
            }
        }
    }

it works fine. That code is adapted from the other examples, but simplified as it's not using the `support::start_loop` function.

Should I go ahead and change the tutorial code? Or is there a reason why it should be using `is_closed()`?

**Comment by tomaka** [comment]
It's using `is_closed()` because it's simpler.
I guess it's `is_closed` that should actually be fixed rather than the tutorial.

**Comment by Sardtok** [comment]
I'm having the same problem on Windows 8.1. I have to kill the examples with Ctrl-C in the console. is_closed seems to return false even after the window is closed. I haven't tried running it outside a command line interface.
