### ISSUE TITLE
Basic triangle drawing not working on OSX

### ISSUE THREAD

**Issue by TyOverby** [tomaka/glium#849]
This is not the triangles drawing example that you have in `glium`, it's a triangle program that I built in my engine.

When running the program normally, nothing shows up on the screen.  When I inserted a bunch of calls to `assert_no_errors`, I get `GL_INVALID_OPERATION` after a call to `frame.draw`.

There should be minor differences between how my `triangles.rs` example and your `triangles.rs` example do things under the scene, so I wonder if you can deduce anything. 

Trace file here: https://www.dropbox.com/s/lsa63yj35hso69e/triangle.trace?dl=0

**Comment by tomaka** [comment]
I only see basic operations in your trace file :-/

Could you try using XCode's debugging tool to see what's wrong?

> Under Mac OS X, Apple provides two very handy tools for debugging OpenGL applications as part of XCode: "OpenGL Driver Monitor" and "OpenGL Profiler".

**Comment by TyOverby** [comment]
Ok, I found out what is causing the issue, though I'm still not sure *why* it's an issue.  I have a custom impl of `ToIndicesSource` that looks like this:

```rust
struct Indices<'a, T: 'a + glium::index::Index> {
    idxs: Option<&'a [T]>,
    prim: glium::index::PrimitiveType
}

impl <'a, T: 'a + glium::index::Index> Indices<'a, T> {
    fn new(prim: glium::index::PrimitiveType, idxs: Option<&'a [T]>) -> Indices<'a, T> {
        Indices {
            idxs: idxs,
            prim: prim
        }
    }
}

impl <'a, T: 'a + glium::index::Index> glium::index::ToIndicesSource for Indices<'a, T> {
    type Data = T;
    fn to_indices_source<'b>(&'b self) -> glium::index::IndicesSource<'b, T> {
        match self.idxs {
            Some(slice) => {
                glium::index::IndicesSource::Buffer {
                    pointer: slice,
                    primitives: self.prim,
                    offset: 0,
                    length: slice.len()
                }
            }
            None => {
                glium::index::IndicesSource::NoIndices {
                    primitives: self.prim
                }
            }
        }
    }
}
```

Apparently the mac drivers don't like that for some reason, while they are fine with your usage of 

```rust
let index_buffer = glium::IndexBuffer::new(&disp,
    glium::index::TrianglesList(vec![0u16, 1, 2]));
```

Sadly, the OSX opengl tools aren't much help, but I hope this narrows things down for you.

**Comment by tomaka** [comment]
Could you try using `u16`s instead of `u32`s?
If it doesn't work, could you try `let index_buffer = glium::index::TrianglesList(vec![0u16, 1, 2]);` ?

Also, are you sure that the OpenGL error is triggered by the draw and not before?

**Comment by TyOverby** [comment]
> Could you try using u16s instead of u32s?
If it doesn't work, could you try let index_buffer = glium::index::TrianglesList(vec![0u16, 1, 2]); ?

I'll try this now.

> Also, are you sure that the OpenGL error is triggered by the draw and not before?

Yep.  I've inserted assert_no_error calls before and after, and only the post-draw assert triggers.

**Comment by TyOverby** [comment]
> using u16s instead of u32s

This doesn't work.

> index_buffer = glium::index::TrianglesList(vec![0u16, 1, 2]); 

This doesn't work either.

It looks like the only thing that works is using the IndexBuffer.

**Comment by tomaka** [comment]
For the record, here is the trace:

![trace](http://i.imgur.com/wW7i2ao.png)

The draw function starts at `glGenVertexArrays` and ends at `glDrawElements`.
Maybe for some reason the call the triggers the OpenGL error hasn't been recorded by by apitrace, but that's all I can see.

**Comment by tomaka** [comment]
Could you produce a trace with the index buffer, to compare the traces?

**Comment by TyOverby** [comment]
Is there a way to query which opengl version glutin picked during the builder phase?  Maybe I'm using an opengl version that only allows for IndexBuffers?

> Could you produce a trace with the index buffer, to compare the traces?

Sure, I'll get that.

**Comment by tomaka** [comment]
Indices in RAM can be used since the beginning of OpenGL, it's index buffers that have been added later.

For the OpenGL version, you can call `println!("{:?}", display.get_opengl_version());`.

**Comment by TyOverby** [comment]
Here's the new trace. 
https://www.dropbox.com/s/viw1gcywhmbm373/triangle.1.trace?dl=0

I'll see what the version that I'm using is.

**Comment by TyOverby** [comment]
If you are curious, I'm on `Version(Gl, 4, 1)`

**Comment by tomaka** [comment]
Duuuh, I found the bug.
It doesn't call `glBindBuffer(GL_ARRAY_BUFFER, ...)`.

**Comment by tomaka** [comment]
Actually, nevermind. It doesn't necessarly need to call `glBindBuffer`.
There are several tests in `indices.rs` that use indices in RAM, and they wouldn't pass if the error was so stupid.

I'll still try a fix so you can tell me if it works.

**Comment by TyOverby** [comment]
Ok, and yeah, this code of mine works fine on all of the linux and windows computers that I have access to.  Just not my macbook.

**Comment by tomaka** [comment]
I found the answer: indices in RAM are just not supported in core OpenGL. It works on Windows and Linux because they are backward-compatible with OpenGL 1.0, and OS/X doesn't support this backward-compatibility.

> An INVALID_OPERATION error is generated if  zero is bound to DRAW_-INDIRECT_BUFFER, or if  no element array buffer is bound.

This was taken from the official OpenGL specifications. Unfortunately the website docs.gl that I usually use as a reference doesn't show this.

**Comment by tomaka** [comment]
Note that performance-wise it is probably faster to use an index buffer, even if you reupload it every time.

**Comment by TyOverby** [comment]
Huh, interesting.  Are you going to remove "from ram" indices from glium then?

Also, can I make index buffers, make a draw call, and then immediately drop the glium IndexBuffer?

**Comment by tomaka** [comment]
> Huh, interesting. Are you going to remove "from ram" indices from glium then?

Yeah, #852 

> Also, can I make index buffers, make a draw call, and then immediately drop the glium IndexBuffer?

Yes. For maximum performances you should reuse the same one though.

**Comment by TyOverby** [comment]
Cool, thanks for your help diagnosing this!
