### ISSUE TITLE
Cannot call XXXTextureXXXArray::new, compile error.

### ISSUE THREAD

**Issue by tioover** [tomaka/glium#874]
src/main.rs:135:35: 135:54 error: no associated item named `new` found for type `glium::texture::Texture2dArray` in the current scope
    src/main.rs:135     let texture: Texture2dArray = Texture2dArray::new(&display, vec![image]);
                                                      ^~~~~~~~~~~~~~~~~~~
    error: aborting due to previous error

and

    src/main.rs:135:19: 135:52 error: no associated item named `new` found for type `glium::texture::CompressedSrgbTexture2dArray` in the current scope
    src/main.rs:135     let texture = CompressedSrgbTexture2dArray::new(&display, vec![image]);
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    error: aborting due to previous error

**Comment by tioover** [comment]
http://tomaka.github.io/glium/glium/texture/struct.Texture2dArray.html#method.new

**Comment by tomaka** [comment]
Is your version of glium up-to-date?
The docs are automatically generated after each commit, so If the docs says it exists, then it exists.

Note that for now will probably have to use the github version if you want to use texture arrays, as it was fixed in #871 an hour ago.

**Comment by Esption** [comment]
@tioover Use new_if_supported().unwrap()

I'm not sure why (I'll need to look into it) but just new() doesn't work.

**Comment by Esption** [comment]
Also, as @tomaka said, this would panic!() until yesterday, it should work now if you're using the git version.  If you're using the latest glium on crates.io, it will panic when running, but it should still compile.  Won't need to use git version when @tomaka next pushes a version (which seems to be every 5 days, so on the 22nd).

**Comment by Esption** [comment]
Okay, looked at the build, ```new()``` needs ```feature = ["gl_texture_3d"]``` in Cargo.toml, while ```new_if_supported()``` doesn't.

Probably a bug, will try to fix and add doc to Texture2dArray to make this more clear.

**Comment by tomaka** [comment]
> @tioover Use new_if_supported(&display, vec![image]).unwrap()
> I'm not sure why (I'll need to look into it) but just new() doesn't work.

Oh, you're totally right. I apologize for what I said.
The reason is that not all backends support texture arrays.

You have two possibilities if you want to use them:

 - Activate the `gl_texture_3d` feature. In this case glium will return an `Err` on initialization if 2D texture arrays are not supported, and allows you to use the `new` function.
 - Use `new_if_supported`.

**Comment by Esption** [comment]
Ah, okay.  Still new to glium's code.  Suggest to add info about it to the doc so it's clearer, though.

**Comment by tomaka** [comment]
Most functions that are behind a Cargo feature have this little notice: http://tomaka.github.io/glium/glium/uniforms/struct.UniformBuffer.html#features

It should eventually be added to textures as well.

**Comment by tioover** [comment]
@tomaka @Esption thank you
