### ISSUE TITLE
panic when attempting to create a shader program that uses quad tessellation

### ISSUE THREAD

**Issue by dylanede** [tomaka/glium#969]
This causes

    thread '<main>' panicked at 'explicit panic', /Users/dylan/repos/glium/src/program/reflection.rs:605

This seems to be due to `OutputPrimitives` not including a member for `Quads`. Adding support for this looks to then require changes in the code for transform feedback.

This problem did not happen in earlier versions before the overhaul to provide support for safe transform feedback.

**Comment by tomaka** [comment]
I think I misread the OpenGL wiki.
Starting transform feedback requires passing the same type of primitive that the primitives generation stage produces. However you can't pass `GL_QUADS`, so I wrongly assumed that you needed a geometry shader if your tessellation evaluation shader outputs quads.
