### ISSUE TITLE
Glium panics on Mac OS Yosemite 10.10.3

### ISSUE THREAD

**Issue by morcmarc** [tomaka/glium#993]
I'm getting the following error when I try to run the examples or my own application: 

```
glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/tomaka/glium/issues
```

The panic is caused by an `assert` in `context/mod.rs` on line 188. `let mut ctxt = context.make_current();` throws a `GL_INVALID_ENUM` somewhere, wasn't able to track it down (haven't got the time at the moment).

I'm happy to look into the issue a bit later, just wanted to ask if anyone has come across this before.

My spec:

- MacBook Pro (15-inch, Mid 2012)
- Yosemite 10.10.3
- CPU: 2.3 GHz Intel Core i7
- GPU No.1: Intel HD Graphics 4000
- GPU No.2: NVIDIA GeForce GT 650M

**Comment by tomaka** [comment]
Thanks for reporting!
I have just added this assertion yesterday, so you're the first.

I'm afraid it comes from `glGetFramebufferParameteriv`. This function is known to be buggy and I've been trying to avoid using it, but there's no alternative on OS/X.

**Comment by dgopstein** [comment]
Oops, I just opened a dup of this: #994

**Comment by tomaka** [comment]
Some infos about the exact location of the OpenGL error would be helpful. I think XCode has an integrated OpenGL debugger.

My guess is that it comes from `glGetFramebufferParameteriv` for the depth and stencil buffers, so I attempted a fix in #995 but I'm not sure if that's the cause.

**Comment by dgopstein** [comment]
Unfortunately the panic still reproduces for me on the `fix-capabilities` branch :/

**Comment by tomaka** [comment]
If XCode doesn't work, there's an alternative way to find the cause.

Could you please:
 - At [this line](https://github.com/tomaka/glium/blob/f310d2d6f46e09b819a8beefbd46228a0f51226a/Cargo.toml#L55) replace `0.0.25` with `0.0.27`
 - At [this line](https://github.com/tomaka/glium/blob/f310d2d6f46e09b819a8beefbd46228a0f51226a/build/main.rs#L111) replace `StructGenerator` with `DebugStructGenerator`
 - Run the faulty code

That should print the list of OpenGL functions being executed and potential errors to stdout.

**Comment by dgopstein** [comment]
```
[OpenGL] GetString(7938)
[OpenGL] GetIntegerv(33309, 0x7fff523b2b68)
[OpenGL] GetStringi(7939, 0)
[OpenGL] GetStringi(7939, 1)
[OpenGL] GetStringi(7939, 2)
[OpenGL] GetStringi(7939, 3)
[OpenGL] GetStringi(7939, 4)
[OpenGL] GetStringi(7939, 5)
[OpenGL] GetStringi(7939, 6)
[OpenGL] GetStringi(7939, 7)
[OpenGL] GetStringi(7939, 8)
[OpenGL] GetStringi(7939, 9)
[OpenGL] GetStringi(7939, 10)
[OpenGL] GetStringi(7939, 11)
[OpenGL] GetStringi(7939, 12)
[OpenGL] GetStringi(7939, 13)
[OpenGL] GetStringi(7939, 14)
[OpenGL] GetStringi(7939, 15)
[OpenGL] GetStringi(7939, 16)
[OpenGL] GetStringi(7939, 17)
[OpenGL] GetStringi(7939, 18)
[OpenGL] GetStringi(7939, 19)
[OpenGL] GetStringi(7939, 20)
[OpenGL] GetStringi(7939, 21)
[OpenGL] GetStringi(7939, 22)
[OpenGL] GetStringi(7939, 23)
[OpenGL] GetStringi(7939, 24)
[OpenGL] GetStringi(7939, 25)
[OpenGL] GetStringi(7939, 26)
[OpenGL] GetStringi(7939, 27)
[OpenGL] GetStringi(7939, 28)
[OpenGL] GetStringi(7939, 29)
[OpenGL] GetStringi(7939, 30)
[OpenGL] GetStringi(7939, 31)
[OpenGL] GetStringi(7939, 32)
[OpenGL] GetStringi(7939, 33)
[OpenGL] GetStringi(7939, 34)
[OpenGL] GetStringi(7939, 35)
[OpenGL] GetStringi(7939, 36)
[OpenGL] GetStringi(7939, 37)
[OpenGL] GetStringi(7939, 38)
[OpenGL] GetStringi(7939, 39)
[OpenGL] GetStringi(7939, 40)
[OpenGL] GetStringi(7939, 41)
[OpenGL] GetStringi(7939, 42)
[OpenGL] GetStringi(7939, 43)
[OpenGL] GetStringi(7939, 44)
[OpenGL] GetStringi(7939, 45)
[OpenGL] GetBooleanv(3123, 0x7fff523b3a3f)
[OpenGL] GetFramebufferAttachmentParameteriv(36160, 1026, 33296, 0x7fff523b3a38)
[OpenGL] GetIntegerv(3414, 0x7fff523b3a30)
[OpenGL] ^ GL error triggered: 1280
[OpenGL] GetIntegerv(3415, 0x7fff523b3998)
[OpenGL] ^ GL error triggered: 1280
[OpenGL] GetIntegerv(35661, 0x7fff523b3980)
[OpenGL] GetFloatv(34047, 0x7fff523b397c)
[OpenGL] GetIntegerv(3386, 0x7fff523b3970)
[OpenGL] GetIntegerv(34852, 0x7fff523b3948)
[OpenGL] GetIntegerv(36477, 0x7fff523b3940)
[OpenGL] GetIntegerv(36464, 0x7fff523b3928)
[OpenGL] GetIntegerv(35375, 0x7fff523b391c)
[OpenGL] GetError()
[OpenGL] Finish()
```

**Comment by tomaka** [comment]
Thanks! That's not what I expected!

**Comment by tomaka** [comment]
I have updated the `fix-capabilities` branch.

**Comment by dgopstein** [comment]
Success! The current `fix-capabilities` branch does not panic with my test code. Thank you!
