### ISSUE TITLE
GL_INVALID_ENUM in build_glium

### ISSUE THREAD

**Issue by dgopstein** [tomaka/glium#994]
I'm getting a panic from a very simple test app.

Glium reports:

    thread '<main>' panicked at 'glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/tomaka/glium/issues', /Users/user/glium/src/context/mod.rs:188

This happens while calling `build_glium()` in the following sample:

```rust
extern crate glium;

fn main() {
    use glium::DisplayBuild;

    let builder = glium::glutin::WindowBuilder::new();

    let _display = builder.build_glium();
}
```

Some simple debugging indicates the underlying error is a `GL_INVALID_ENUM`, but I've yet to identify the root cause.

I'm using a clone of the glium source from earlier today. Running on OSX.

Still pretty new at this, but please let me know what other information I can provide. Thanks!

**Comment by dgopstein** [comment]
Dup of #993

**Comment by tomaka** [comment]
Thanks for reporting. Closing as a duplicate.
