### ISSUE TITLE
Allow passing pre-calculated mipmaps

### ISSUE THREAD

**Issue by thelink2012** [tomaka/glium#997]
Quoting @tomaka in a random PR:
> For the moment mipmaps can only be auto-generated by glium (I know this is a problem).
Calling glGenerateMipmaps is forbidden with compressed textures, so if I didn't have this line it would end up generating an OpenGL error.
>
>In my opinion this should eventually be changed to give the user four possibilities:
>
>   * Give data for mipmaps in the Texture*dDataSource traits.
>   * Auto-generate mipmaps.
>   * Only upload the main texture and create empty mipmaps.
>   * No mipmaps.
>
> However the API would need some thinking.

**Comment by thelink2012** [comment]
That'd cause API breakage but what if the `mipmaps: bool` parameter on a few constructors was replace by a enum specifying what to do about the mips (options exposed in the OP quote)? Then add methods to the _*Texture*Mipmap _ types to upload (and even download) the mipmap data of that level.

**Comment by tomaka** [comment]
> Then add methods to the _TextureMipmap _ types to upload (and even download) the mipmap data of that level.

That's what I was planning to do. I was blocked by the fact that glium needs to determine the dimensions of the mipmaps. I don't know if it's safe to calculate it manually or if we need to retreive them from OpenGL.

> That'd cause API breakage but what if the mipmaps: bool parameter on a few constructors was replace by a enum specifying what to do about the mips (options exposed in the OP quote)?

It's the right moment for a breakage. I have some other breaking changes in queue for version 0.6.

There are a few unsolved questions:

 - Should the `Texture2dDataSource` trait provide the data for the mipmaps, or should the user pass multiple objects that each implement `Texture2dDataSource`, one per mipmap?
 - One of the options would be "auto-generated mipmaps", but compressed textures shouldn't get that option. I guess we'll have to use an enum for compressed textures and another one for the rest?

**Comment by thelink2012** [comment]
>Should the Texture2dDataSource trait provide the data for the mipmaps, or should the user pass multiple objects that each implement Texture2dDataSource, one per mipmap?

Plus what about the compressed data input, that is a `&[u8]` instead of a data source?

Passing the mips on the main level constructor seems complicated, perhaps leave just the option to upload from the object of each level.

>One of the options would be "auto-generated mipmaps", but compressed textures shouldn't get that option. I guess we'll have to use an enum for compressed textures and another one for the rest?

Or maybe assert in case auto-generate is passed to compressed ones. It all comes down to if we want compile or runtime/documentation guarantees. I'd pick the former but I'm always afraid of pollution.

>I was stopped in my tracks by the fact that glium needs to determine the dimensions of the mipmaps. I don't know if it's safe to calculate it manually or if we need to retreive them from OpenGL.

It seems to be safe and well defined, from [glspec45 §8.14. TEXTURE MINIFICATION](https://www.opengl.org/registry/doc/glspec45.core.pdf#page=663):

> Level-of-detail numbers proceed from levelbase for the original texture  image  through  the  maximum  level p, with  each  unit  increase  indicating an  array  of  half  the  dimensions  of  the  previous  one  (rounded  down  to  the  next integer if fractional).

**Comment by tomaka** [comment]
I agree with letting the user manually upload each mipmap.

So as you suggested I think the API should look like this:

```rust
pub enum MipmapsGenerationOption {
    NoMipmap,
    EmptyMipmaps,
    EmptyMipmapsCount(u32),
    AutoGeneratedMipmaps,
    AutoGeneratedMipmapsCount(u32),
}

impl Texture2d {
    pub fn new<D>(data: D) { ... }     // same as with_mipmaps(data, AutoGeneratedMipmaps)

    pub fn with_mipmaps<D>(data: D, mipmaps: MipmapGenerationOption) { ... }

    pub fn with_format<D>(data: D, format: FloatFormat, mipmaps: MipmapGenerationOption) { ... }
}
```

But for compressed textures, it would be slightly different:

```rust
pub enum CompressedMipmapsGenerationOption {
    NoMipmap,
    EmptyMipmaps,
    EmptyMipmapsCount(u32),
}

impl CompressedTexture2d {
    pub fn new<D>(data: D) { ... }     // same as with_mipmaps(data, EmptyMipmaps)

    pub fn with_mipmaps<D>(data: D, mipmaps: CompressedMipmapsGenerationOption) { ... }

    pub fn with_format<D>(data: D, format: CompressedFormat, mipmaps: CompressedMipmapsGenerationOption) { ... }
}
```

**Comment by tomaka** [comment]
It could even be implemented in a backward-compatible way if we added `impl From<bool> for MipmapsGenerationOption`.

**Comment by thelink2012** [comment]
I should come with a PR for this soon then.
