### ISSUE TITLE
panicked during initialization

### ISSUE THREAD

**Issue by ConnyOnny** [tomaka/glium#998]
Hi, I used the exact example code to show a blank window from here: http://tomaka.github.io/glium/glium/index.html
This is what I get:
`thread '<main>' panicked at 'glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/tomaka/glium/issues', /home/c/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.5.5/src/context/mod.rs:188`
I'm on an Intel IGPU running Debian Testing with a compositing window manager under Xorg and other OpenGL applications (even games) work fine.

**Comment by tomaka** [comment]
Hi. What does `glxinfo` say?

**Comment by ConnyOnny** [comment]
Works now. Thank you for the fix.
